// SPDX-License-Identifier: Apache-2.0
//! Named node kinds admitted by the deltas framing grammar.

/// Named Parasolid node kind, independent of full-record payload form.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum RecordKind {
    Body = 12,
    Shell = 13,
    Face = 14,
    Loop = 15,
    Edge = 16,
    Fin = 17,
    Vertex = 18,
    Region = 19,
    Point = 29,
    Line = 30,
    Circle = 31,
    Ellipse = 32,
    Intersection = 38,
    Chart = 40,
    TermUse = 41,
    Type45 = 45,
    Plane = 50,
    Cylinder = 51,
    Cone = 52,
    Sphere = 53,
    Torus = 54,
    BlendSurf = 56,
    BlendBound = 59,
    OffsetSurf = 60,
    Type67 = 67,
    Type70 = 70,
    AttdefList = 74,
    Entity51 = 81,
    Entity52 = 82,
    Entity53 = 83,
    Entity54 = 84,
    Entity55 = 85,
    Entity56 = 86,
    Entity57 = 87,
    Entity58 = 88,
    Entity59 = 89,
    Entity62 = 98,
    Group = 90,
    Type91 = 91,
    Type101 = 101,
    BSurface = 124,
    BSurfaceData = 125,
    BSurfaceDescriptor = 126,
    Multiplicities = 127,
    Knots = 128,
    TrimmedCurve = 133,
    BCurve = 134,
    BCurveData = 135,
    BCurveDescriptor = 136,
    SpCurve = 137,
    Type141 = 141,
    SupportUv = 204,
}

impl RecordKind {
    pub const fn code(self) -> u8 {
        self as u8
    }

    pub const fn name(self) -> &'static str {
        match self {
            Self::Body => "BODY",
            Self::Shell => "SHELL",
            Self::Face => "FACE",
            Self::Loop => "LOOP",
            Self::Edge => "EDGE",
            Self::Fin => "FIN",
            Self::Vertex => "VERTEX",
            Self::Region => "REGION",
            Self::Point => "POINT",
            Self::Line => "LINE",
            Self::Circle => "CIRCLE",
            Self::Ellipse => "ELLIPSE",
            Self::Intersection => "INTERSECTION",
            Self::Chart => "CHART",
            Self::TermUse => "TERM_USE",
            Self::Type45 => "TYPE_45",
            Self::Plane => "PLANE",
            Self::Cylinder => "CYLINDER",
            Self::Cone => "CONE",
            Self::Sphere => "SPHERE",
            Self::Torus => "TORUS",
            Self::BlendSurf => "BLEND_SURF",
            Self::BlendBound => "BLEND_BOUND",
            Self::OffsetSurf => "OFFSET_SURF",
            Self::Type67 => "TYPE_67",
            Self::Type70 => "TYPE_70",
            Self::AttdefList => "ATTDEF_LIST",
            Self::Entity51 => "ENTITY_51",
            Self::Entity52 => "ENTITY_52",
            Self::Entity53 => "ENTITY_53",
            Self::Entity54 => "ENTITY_54",
            Self::Entity55 => "ENTITY_55",
            Self::Entity56 => "ENTITY_56",
            Self::Entity57 => "ENTITY_57",
            Self::Entity58 => "ENTITY_58",
            Self::Entity59 => "ENTITY_59",
            Self::Entity62 => "ENTITY_62",
            Self::Group => "GROUP",
            Self::Type91 => "TYPE_91",
            Self::Type101 => "TYPE_101",
            Self::BSurface => "B_SURFACE",
            Self::BSurfaceData => "B_SURFACE_DATA",
            Self::BSurfaceDescriptor => "B_SURFACE_DESCRIPTOR",
            Self::Multiplicities => "MULTIPLICITIES",
            Self::Knots => "KNOTS",
            Self::TrimmedCurve => "TRIMMED_CURVE",
            Self::BCurve => "B_CURVE",
            Self::BCurveData => "B_CURVE_DATA",
            Self::BCurveDescriptor => "B_CURVE_DESCRIPTOR",
            Self::SpCurve => "SP_CURVE",
            Self::Type141 => "TYPE_141",
            Self::SupportUv => "SUPPORT_UV",
        }
    }
}

impl TryFrom<u16> for RecordKind {
    type Error = &'static str;
    fn try_from(code: u16) -> Result<Self, Self::Error> {
        match code {
            12 => Ok(Self::Body),
            13 => Ok(Self::Shell),
            14 => Ok(Self::Face),
            15 => Ok(Self::Loop),
            16 => Ok(Self::Edge),
            17 => Ok(Self::Fin),
            18 => Ok(Self::Vertex),
            19 => Ok(Self::Region),
            29 => Ok(Self::Point),
            30 => Ok(Self::Line),
            31 => Ok(Self::Circle),
            32 => Ok(Self::Ellipse),
            38 => Ok(Self::Intersection),
            40 => Ok(Self::Chart),
            41 => Ok(Self::TermUse),
            45 => Ok(Self::Type45),
            50 => Ok(Self::Plane),
            51 => Ok(Self::Cylinder),
            52 => Ok(Self::Cone),
            53 => Ok(Self::Sphere),
            54 => Ok(Self::Torus),
            56 => Ok(Self::BlendSurf),
            59 => Ok(Self::BlendBound),
            60 => Ok(Self::OffsetSurf),
            67 => Ok(Self::Type67),
            70 => Ok(Self::Type70),
            74 => Ok(Self::AttdefList),
            81 => Ok(Self::Entity51),
            82 => Ok(Self::Entity52),
            83 => Ok(Self::Entity53),
            84 => Ok(Self::Entity54),
            85 => Ok(Self::Entity55),
            86 => Ok(Self::Entity56),
            87 => Ok(Self::Entity57),
            88 => Ok(Self::Entity58),
            89 => Ok(Self::Entity59),
            98 => Ok(Self::Entity62),
            90 => Ok(Self::Group),
            91 => Ok(Self::Type91),
            101 => Ok(Self::Type101),
            124 => Ok(Self::BSurface),
            125 => Ok(Self::BSurfaceData),
            126 => Ok(Self::BSurfaceDescriptor),
            127 => Ok(Self::Multiplicities),
            128 => Ok(Self::Knots),
            133 => Ok(Self::TrimmedCurve),
            134 => Ok(Self::BCurve),
            135 => Ok(Self::BCurveData),
            136 => Ok(Self::BCurveDescriptor),
            137 => Ok(Self::SpCurve),
            141 => Ok(Self::Type141),
            204 => Ok(Self::SupportUv),
            _ => Err("unknown deltas node kind"),
        }
    }
}
