// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// Unit tests compare this registry-owned list with the codec-owned enum.

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 11] = [
    DialectId::pinned("rhino:archive-1"),
    DialectId::pinned("rhino:archive-2"),
    DialectId::pinned("rhino:archive-3"),
    DialectId::pinned("rhino:archive-4"),
    DialectId::pinned("rhino:archive-5"),
    DialectId::pinned("rhino:archive-50"),
    DialectId::pinned("rhino:archive-60"),
    DialectId::pinned("rhino:archive-70"),
    DialectId::pinned("rhino:archive-80"),
    DialectId::pinned("rhino:archive-90"),
    DialectId::pinned("rhino:unknown"),
];
