// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// The generated row array is checked as an artifact, not read at runtime.
#![allow(dead_code)]

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const ARCHIVE_1_STR: &str = "rhino:archive-1";
#[rustfmt::skip]
pub(super) const ARCHIVE_1: DialectId = DialectId::pinned(ARCHIVE_1_STR);
#[rustfmt::skip]
pub(super) const ARCHIVE_2_STR: &str = "rhino:archive-2";
#[rustfmt::skip]
pub(super) const ARCHIVE_2: DialectId = DialectId::pinned(ARCHIVE_2_STR);
#[rustfmt::skip]
pub(super) const ARCHIVE_3_STR: &str = "rhino:archive-3";
#[rustfmt::skip]
pub(super) const ARCHIVE_3: DialectId = DialectId::pinned(ARCHIVE_3_STR);
#[rustfmt::skip]
pub(super) const ARCHIVE_4_STR: &str = "rhino:archive-4";
#[rustfmt::skip]
pub(super) const ARCHIVE_4: DialectId = DialectId::pinned(ARCHIVE_4_STR);
#[rustfmt::skip]
pub(super) const ARCHIVE_5_STR: &str = "rhino:archive-5";
#[rustfmt::skip]
pub(super) const ARCHIVE_5: DialectId = DialectId::pinned(ARCHIVE_5_STR);
#[rustfmt::skip]
pub(super) const ARCHIVE_50_STR: &str = "rhino:archive-50";
#[rustfmt::skip]
pub(super) const ARCHIVE_50: DialectId = DialectId::pinned(ARCHIVE_50_STR);
#[rustfmt::skip]
pub(super) const ARCHIVE_60_STR: &str = "rhino:archive-60";
#[rustfmt::skip]
pub(super) const ARCHIVE_60: DialectId = DialectId::pinned(ARCHIVE_60_STR);
#[rustfmt::skip]
pub(super) const ARCHIVE_70_STR: &str = "rhino:archive-70";
#[rustfmt::skip]
pub(super) const ARCHIVE_70: DialectId = DialectId::pinned(ARCHIVE_70_STR);
#[rustfmt::skip]
pub(super) const ARCHIVE_80_STR: &str = "rhino:archive-80";
#[rustfmt::skip]
pub(super) const ARCHIVE_80: DialectId = DialectId::pinned(ARCHIVE_80_STR);
#[rustfmt::skip]
pub(super) const ARCHIVE_90_STR: &str = "rhino:archive-90";
#[rustfmt::skip]
pub(super) const ARCHIVE_90: DialectId = DialectId::pinned(ARCHIVE_90_STR);
#[rustfmt::skip]
pub(super) const UNKNOWN_STR: &str = "rhino:unknown";
#[rustfmt::skip]
pub(super) const UNKNOWN: DialectId = DialectId::pinned(UNKNOWN_STR);

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 11] = [
    ARCHIVE_1,
    ARCHIVE_2,
    ARCHIVE_3,
    ARCHIVE_4,
    ARCHIVE_5,
    ARCHIVE_50,
    ARCHIVE_60,
    ARCHIVE_70,
    ARCHIVE_80,
    ARCHIVE_90,
    UNKNOWN,
];
