// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/check-dialects.py from docs/dialects.toml.
// Do not edit this file directly.

/// Registry-owned format namespace.
pub(crate) const FORMAT: &str = "rhino";

/// Registry-owned dialect id `rhino:archive-1`.
pub(crate) const RHINO_ARCHIVE_1: DialectId = cadmpeg_core::dialect_id!("rhino:archive-1");
/// Registry-owned dialect id `rhino:archive-2`.
pub(crate) const RHINO_ARCHIVE_2: DialectId = cadmpeg_core::dialect_id!("rhino:archive-2");
/// Registry-owned dialect id `rhino:archive-3`.
pub(crate) const RHINO_ARCHIVE_3: DialectId = cadmpeg_core::dialect_id!("rhino:archive-3");
/// Registry-owned dialect id `rhino:archive-4`.
pub(crate) const RHINO_ARCHIVE_4: DialectId = cadmpeg_core::dialect_id!("rhino:archive-4");
/// Registry-owned dialect id `rhino:archive-5`.
pub(crate) const RHINO_ARCHIVE_5: DialectId = cadmpeg_core::dialect_id!("rhino:archive-5");
/// Registry-owned dialect id `rhino:archive-50`.
pub(crate) const RHINO_ARCHIVE_50: DialectId = cadmpeg_core::dialect_id!("rhino:archive-50");
/// Registry-owned dialect id `rhino:archive-60`.
pub(crate) const RHINO_ARCHIVE_60: DialectId = cadmpeg_core::dialect_id!("rhino:archive-60");
/// Registry-owned dialect id `rhino:archive-70`.
pub(crate) const RHINO_ARCHIVE_70: DialectId = cadmpeg_core::dialect_id!("rhino:archive-70");
/// Registry-owned dialect id `rhino:archive-80`.
pub(crate) const RHINO_ARCHIVE_80: DialectId = cadmpeg_core::dialect_id!("rhino:archive-80");
/// Registry-owned dialect id `rhino:archive-90`.
pub(crate) const RHINO_ARCHIVE_90: DialectId = cadmpeg_core::dialect_id!("rhino:archive-90");
/// Registry-owned dialect id `rhino:unknown`.
pub(crate) const RHINO_UNKNOWN: DialectId = cadmpeg_core::dialect_id!("rhino:unknown");
