// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// The generated row array is checked as an artifact, not read at runtime.
#![allow(dead_code)]

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const SPLMSSTR_STR: &str = "nx:splmsstr";
#[rustfmt::skip]
pub(super) const SPLMSSTR: DialectId = DialectId::pinned(SPLMSSTR_STR);
#[rustfmt::skip]
pub(super) const LEGACY_CFB_STR: &str = "nx:legacy-cfb";
#[rustfmt::skip]
pub(super) const LEGACY_CFB: DialectId = DialectId::pinned(LEGACY_CFB_STR);
#[rustfmt::skip]
pub(super) const UNKNOWN_STR: &str = "nx:unknown";
#[rustfmt::skip]
pub(super) const UNKNOWN: DialectId = DialectId::pinned(UNKNOWN_STR);

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 3] = [
    SPLMSSTR,
    LEGACY_CFB,
    UNKNOWN,
];
