// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/check-dialects.py from crates/cadmpeg-registry/docs/dialects.toml.
// Do not edit this file directly.

/// Registry-owned format namespace.
pub(crate) const FORMAT: &str = "nx";

/// Registry-owned dialect id `nx:splmsstr`.
pub(crate) const NX_SPLMSSTR: DialectId = cadmpeg_core::dialect_id!("nx:splmsstr");
/// Registry-owned dialect id `nx:legacy-cfb`.
pub(crate) const NX_LEGACY_CFB: DialectId = cadmpeg_core::dialect_id!("nx:legacy-cfb");
