// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/check-dialects.py from docs/dialects.toml.
// Do not edit this file directly.

/// Registry-owned format namespace.
pub(crate) const FORMAT: &str = "nx";

/// Registry-owned dialect id `nx:splmsstr`.
pub(crate) const NX_SPLMSSTR: DialectId = DialectId::pinned("nx:splmsstr");
/// Registry-owned dialect id `nx:legacy-cfb`.
pub(crate) const NX_LEGACY_CFB: DialectId = DialectId::pinned("nx:legacy-cfb");
/// Registry-owned dialect id `nx:unknown`.
// Container detection cannot produce this registry row.
#[allow(dead_code)]
pub(crate) const NX_UNKNOWN: DialectId = DialectId::pinned("nx:unknown");
