// SPDX-License-Identifier: Apache-2.0
//! Design dimension recipe records: loci, annotation frames and presentation frames.

use super::identity::Located;
use super::recipes::ConstructionRecipeKind;
use super::references::DesignClassTag;
use super::sketch_relations::{
    constraint_kinds_from_state, SketchConstraintKind, SKETCH_CONSTRAINT_MASK,
};
use cadmpeg_ir::ids::{EdgeId, FaceId};
use serde::{Deserialize, Deserializer, Serialize};
use std::num::NonZeroU32;

cadmpeg_core::named_optional_field!(
    deserialize_companion_record_index,
    u32,
    "companion_record_index"
);
cadmpeg_core::named_optional_field!(deserialize_opaque_index, u32, "opaque_index");
cadmpeg_core::named_optional_field!(deserialize_opaque_index_offset, u64, "opaque_index_offset");
/// Indexed record that directly contains one construction recipe owned by a
/// dimensional parameter companion.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct DesignDimensionRecipeRecord {
    /// Globally unique deterministic identifier for this native record.
    pub(crate) id: String,
    /// Companion record containing this indexed record.
    pub(crate) companion_record_index: u32,
    /// Deterministic decoder ordinal within the companion payload; it is not a
    /// source operation order.
    pub(crate) recipe_ordinal: u32,
    /// Construction recipe contained by this indexed record.
    pub(crate) recipe_id: String,
    /// Topology kind regenerated by the contained construction recipe.
    pub(crate) recipe_kind: ConstructionRecipeKind,
    /// Byte offset of the indexed record header.
    pub(crate) byte_offset: u64,
    /// Source per-file dynamic three-digit ASCII class tag.
    pub(crate) class_tag: DesignClassTag,
    /// Source indexed-record identity.
    pub(crate) record_index: u32,
    /// Number of bytes from this header to the next indexed header or the end
    /// of the companion-owned payload.
    pub(crate) frame_length: u64,
    /// Byte offset of the recipe-specific prefix after the indexed header.
    pub(crate) prefix_offset: u64,
    /// Complete recipe-specific prefix before the length-prefixed family name.
    #[serde(with = "cadmpeg_ir::bytes")]
    pub(crate) prefix_bytes: Vec<u8>,
    /// Persistent Design selector/reference tails decoded from the prefix.
    pub(crate) references: Vec<DesignRecipeReference>,
    /// Byte offset of the first i32 after the recipe-family name.
    pub(crate) program_offset: u64,
    /// Complete little-endian i32 program through the indexed-record boundary.
    pub(crate) program: Vec<i32>,
    /// Edge operands whose complete post-prologue recipe program occurs as a
    /// contiguous subsequence of this program.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub(crate) matching_edge_operand_ids: Vec<String>,
}

/// One persistent Design selector/reference tail in a dimension recipe.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct DesignRecipeReference {
    /// Native persistent-subentity selector.
    pub(crate) selector: i64,
    /// Byte offset of `selector`.
    pub(crate) selector_offset: u64,
    /// ASCII persistent-subentity selector token.
    pub(crate) token: String,
    /// Byte offset of the token bytes.
    pub(crate) token_offset: u64,
    /// Persistent Design reference paired with `token`.
    pub(crate) design_reference: i64,
    /// Byte offset of `design_reference`.
    pub(crate) design_reference_offset: u64,
    /// Recipe-state faces carrying the token and Design reference.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub(crate) candidate_faces: Vec<FaceId>,
    /// Recipe-state edges carrying the token and Design reference.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub(crate) candidate_edges: Vec<EdgeId>,
    /// Active-BREP faces carrying the token and Design reference under a
    /// different native selector, before a historical state supersedes them.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub(crate) alternate_selector_faces: Vec<FaceId>,
    /// Active-BREP edges carrying the token and Design reference under a
    /// different native selector, before a historical state supersedes them.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub(crate) alternate_selector_edges: Vec<EdgeId>,
}

/// Paired-locus frame nested under a dimensional parameter companion.
///
/// One frame shape covers both source forms: the two-locus form, which carries
/// the opaque index that precedes its loci, and the null-locus form, whose
/// first locus is the fixed zero reference and which carries no opaque index.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    try_from = "DesignDimensionLocusPairWire",
    into = "DesignDimensionLocusPairWire"
)]
pub(crate) struct DesignDimensionLocusPair {
    /// Globally unique deterministic identifier for this native record.
    pub(crate) id: String,
    /// Companion record containing this frame.
    pub(crate) companion_record_index: u32,
    /// Companion owned by the following governed dimension parameter.
    pub(crate) governing_companion_record_index: u32,
    byte_offset: u64,
    /// Per-file primary class tag.
    pub(super) class_tag: DesignClassTag,
    /// Shared logical record identity.
    pub(crate) record_index: u32,
    frame_length: u64,
    first: DimensionFirstLocus,
    second_geometry_record_index: NonZeroU32,
    roles: [u32; 2],
    /// Per-file paired class tag.
    pub(crate) paired_class_tag: DesignClassTag,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum DimensionFirstLocus {
    Null,
    Geometry {
        opaque_index: u32,
        record_index: NonZeroU32,
    },
}

/// Unchecked dimension locus pair payload and frame offsets.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct DesignDimensionLocusPairDraft {
    /// Globally unique deterministic identifier for this native record.
    pub(crate) id: String,
    /// Companion record containing this frame.
    pub(crate) companion_record_index: u32,
    /// Companion record owned by the following dimension parameter governed by
    /// this frame.
    pub(crate) governing_companion_record_index: u32,
    /// Byte offset of the primary indexed record header.
    pub(crate) byte_offset: u64,
    /// Source per-file dynamic three-digit ASCII primary class tag.
    pub(crate) class_tag: DesignClassTag,
    /// Shared logical record identity.
    pub(crate) record_index: u32,
    /// Byte length from the primary header to the paired header.
    pub(crate) frame_length: u64,
    /// Opaque u32 preceding the two locus references. Present exactly when the
    /// first locus names sketch geometry.
    pub(crate) opaque_index: Option<Located<u32>>,
    /// The two ordered loci. `loci[0].geometry_record_index` is `None` in the
    /// null-locus form, where the frame stores a fixed zero record reference.
    pub(crate) loci: [DesignDimensionAnnotationOperand; 2],
    /// Per-file dynamic class tag of the paired header.
    pub(crate) paired_class_tag: DesignClassTag,
    /// Byte offset of the paired indexed record header.
    pub(crate) paired_byte_offset: u64,
}

impl DesignDimensionLocusPair {
    /// Admit one of the two locus frame layouts with representable offsets.
    pub(crate) fn try_new(draft: DesignDimensionLocusPairDraft) -> Result<Self, String> {
        let first = match (
            draft.opaque_index.as_ref(),
            draft.loci[0].geometry_record_index,
        ) {
            (None, None) => DimensionFirstLocus::Null,
            (Some(opaque), Some(record_index)) => DimensionFirstLocus::Geometry {
                opaque_index: opaque.value,
                record_index,
            },
            _ => return Err(
                "opaque_index is present exactly when first_geometry_record_index names geometry"
                    .into(),
            ),
        };
        let second_geometry_record_index = draft.loci[1]
            .geometry_record_index
            .ok_or("second_geometry_record_index must name an indexed sketch-geometry record")?;
        let prefix = match first {
            DimensionFirstLocus::Null => 25,
            DimensionFirstLocus::Geometry { .. } => 40,
        };
        if draft.frame_length <= prefix + 29 {
            return Err("frame_length does not contain the complete locus frame".into());
        }
        let paired_byte_offset = draft
            .byte_offset
            .checked_add(draft.frame_length)
            .ok_or("paired_byte_offset overflows")?;
        if draft.paired_byte_offset != paired_byte_offset {
            return Err("paired_byte_offset disagrees with frame_length".into());
        }
        if draft
            .opaque_index
            .as_ref()
            .is_some_and(|opaque| opaque.offset != draft.byte_offset + 35)
        {
            return Err("opaque_index_offset disagrees with byte_offset".into());
        }
        for (ordinal, locus) in draft.loci.iter().enumerate() {
            let offset = draft.byte_offset + prefix + ordinal as u64 * 15;
            let field = if ordinal == 0 { "first" } else { "second" };
            if locus.geometry_reference_offset != offset {
                return Err(format!(
                    "{field}_geometry_reference_offset disagrees with byte_offset"
                ));
            }
            if locus.role_offset != offset + 10 {
                return Err(format!("{field}_role_offset disagrees with byte_offset"));
            }
        }
        Ok(Self {
            id: draft.id,
            companion_record_index: draft.companion_record_index,
            governing_companion_record_index: draft.governing_companion_record_index,
            byte_offset: draft.byte_offset,
            class_tag: draft.class_tag,
            record_index: draft.record_index,
            frame_length: draft.frame_length,
            first,
            second_geometry_record_index,
            roles: [draft.loci[0].role, draft.loci[1].role],
            paired_class_tag: draft.paired_class_tag,
        })
    }

    /// Primary indexed header byte offset.
    pub(crate) fn byte_offset(&self) -> u64 {
        self.byte_offset
    }

    /// Length from the primary header to the paired header.
    pub(crate) fn frame_length(&self) -> u64 {
        self.frame_length
    }

    /// Paired indexed header byte offset.
    pub(crate) fn paired_byte_offset(&self) -> u64 {
        self.byte_offset + self.frame_length
    }

    /// Opaque index and its derived offset in the ordinary two-locus form.
    pub(super) fn opaque_index(&self) -> Option<Located<u32>> {
        match self.first {
            DimensionFirstLocus::Null => None,
            DimensionFirstLocus::Geometry { opaque_index, .. } => Some(Located {
                value: opaque_index,
                offset: self.byte_offset + 35,
            }),
        }
    }

    /// Ordered loci and their derived geometry and role offsets.
    pub(crate) fn loci(&self) -> [DesignDimensionAnnotationOperand; 2] {
        let (first, prefix) = match self.first {
            DimensionFirstLocus::Null => (None, 25),
            DimensionFirstLocus::Geometry { record_index, .. } => (Some(record_index), 40),
        };
        [
            DesignDimensionAnnotationOperand {
                geometry_record_index: first,
                geometry_reference_offset: self.byte_offset + prefix,
                role: self.roles[0],
                role_offset: self.byte_offset + prefix + 10,
            },
            DesignDimensionAnnotationOperand {
                geometry_record_index: Some(self.second_geometry_record_index),
                geometry_reference_offset: self.byte_offset + prefix + 15,
                role: self.roles[1],
                role_offset: self.byte_offset + prefix + 25,
            },
        ]
    }

    /// Recover the payload with derived frame and locus offsets.
    pub(crate) fn into_draft(self) -> DesignDimensionLocusPairDraft {
        let opaque_index = self.opaque_index();
        let loci = self.loci();
        let paired_byte_offset = self.paired_byte_offset();
        DesignDimensionLocusPairDraft {
            id: self.id,
            companion_record_index: self.companion_record_index,
            governing_companion_record_index: self.governing_companion_record_index,
            byte_offset: self.byte_offset,
            class_tag: self.class_tag,
            record_index: self.record_index,
            frame_length: self.frame_length,
            opaque_index,
            loci,
            paired_class_tag: self.paired_class_tag,
            paired_byte_offset,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(super) struct DesignDimensionLocusPairWire {
    pub(super) id: String,
    pub(super) companion_record_index: u32,
    pub(super) governing_companion_record_index: u32,
    pub(super) byte_offset: u64,
    pub(super) class_tag: String,
    pub(super) record_index: u32,
    pub(super) frame_length: u64,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_opaque_index"
    )]
    pub(super) opaque_index: Option<u32>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_opaque_index_offset"
    )]
    pub(super) opaque_index_offset: Option<u64>,
    pub(super) first_geometry_record_index: u32,
    pub(super) first_geometry_reference_offset: u64,
    pub(super) first_role: u32,
    pub(super) first_role_offset: u64,
    pub(super) second_geometry_record_index: u32,
    pub(super) second_geometry_reference_offset: u64,
    pub(super) second_role: u32,
    pub(super) second_role_offset: u64,
    pub(super) paired_class_tag: String,
    pub(super) paired_byte_offset: u64,
}

impl TryFrom<DesignDimensionLocusPairWire> for DesignDimensionLocusPair {
    type Error = String;

    fn try_from(wire: DesignDimensionLocusPairWire) -> Result<Self, Self::Error> {
        let opaque_index = match (wire.opaque_index, wire.opaque_index_offset) {
            (None, None) => None,
            (Some(value), Some(offset)) => Some(Located { value, offset }),
            _ => return Err("opaque_index and opaque_index_offset must occur together".to_owned()),
        };
        let first = NonZeroU32::new(wire.first_geometry_record_index);
        let second = NonZeroU32::new(wire.second_geometry_record_index);
        Self::try_new(DesignDimensionLocusPairDraft {
            id: wire.id,
            companion_record_index: wire.companion_record_index,
            governing_companion_record_index: wire.governing_companion_record_index,
            byte_offset: wire.byte_offset,
            class_tag: wire.class_tag.try_into()?,
            record_index: wire.record_index,
            frame_length: wire.frame_length,
            opaque_index,
            loci: [
                DesignDimensionAnnotationOperand {
                    geometry_record_index: first,
                    geometry_reference_offset: wire.first_geometry_reference_offset,
                    role: wire.first_role,
                    role_offset: wire.first_role_offset,
                },
                DesignDimensionAnnotationOperand {
                    geometry_record_index: second,
                    geometry_reference_offset: wire.second_geometry_reference_offset,
                    role: wire.second_role,
                    role_offset: wire.second_role_offset,
                },
            ],
            paired_class_tag: wire.paired_class_tag.try_into()?,
            paired_byte_offset: wire.paired_byte_offset,
        })
    }
}

impl From<DesignDimensionLocusPair> for DesignDimensionLocusPairWire {
    fn from(pair: DesignDimensionLocusPair) -> Self {
        let pair = pair.into_draft();
        let [first, second] = pair.loci;
        Self {
            id: pair.id,
            companion_record_index: pair.companion_record_index,
            governing_companion_record_index: pair.governing_companion_record_index,
            byte_offset: pair.byte_offset,
            class_tag: pair.class_tag.into(),
            record_index: pair.record_index,
            frame_length: pair.frame_length,
            opaque_index: pair.opaque_index.as_ref().map(|located| located.value),
            opaque_index_offset: pair.opaque_index.as_ref().map(|located| located.offset),
            first_geometry_record_index: first.geometry_record_index.map_or(0, NonZeroU32::get),
            first_geometry_reference_offset: first.geometry_reference_offset,
            first_role: first.role,
            first_role_offset: first.role_offset,
            second_geometry_record_index: second.geometry_record_index.map_or(0, NonZeroU32::get),
            second_geometry_reference_offset: second.geometry_reference_offset,
            second_role: second.role,
            second_role_offset: second.role_offset,
            paired_class_tag: pair.paired_class_tag.into(),
            paired_byte_offset: pair.paired_byte_offset,
        }
    }
}

/// One nullable typed operand in an annotated dimension frame.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct DesignDimensionAnnotationOperand {
    /// Indexed sketch geometry record, absent for the null locus.
    #[serde(with = "annotation_geometry_index")]
    pub(crate) geometry_record_index: Option<NonZeroU32>,
    /// Byte offset of `geometry_record_index`.
    pub(crate) geometry_reference_offset: u64,
    /// Source dimension-role code.
    pub(crate) role: u32,
    /// Byte offset of `role`.
    pub(crate) role_offset: u64,
}

impl DesignDimensionAnnotationOperand {
    /// The named sketch-geometry record, or the wire's zero for the null locus.
    pub(crate) fn geometry_index(&self) -> u32 {
        self.geometry_record_index.map_or(0, NonZeroU32::get)
    }
}

mod annotation_geometry_index {
    use serde::{Deserialize, Deserializer, Serialize, Serializer};
    use std::num::NonZeroU32;

    // The wire adapter receives the optional field by reference, including its absence.
    // Serde passes the field by reference to this wire adapter.
    #[allow(clippy::ref_option, clippy::trivially_copy_pass_by_ref)]
    pub(super) fn serialize<S: Serializer>(
        index: &Option<NonZeroU32>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        match index {
            Some(index) => index.get(),
            None => 0,
        }
        .serialize(serializer)
    }

    pub(super) fn deserialize<'de, D: Deserializer<'de>>(
        deserializer: D,
    ) -> Result<Option<NonZeroU32>, D::Error> {
        Ok(NonZeroU32::new(u32::deserialize(deserializer)?))
    }
}

/// One required geometry operand in a dimension presentation frame.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct DesignDimensionPresentationOperand {
    /// Indexed sketch geometry record.
    #[serde(deserialize_with = "deserialize_presentation_geometry_index")]
    pub(crate) geometry_record_index: NonZeroU32,
    /// Byte offset of `geometry_record_index`.
    pub(crate) geometry_reference_offset: u64,
    /// Source dimension-role code.
    pub(crate) role: u32,
    /// Byte offset of `role`.
    pub(crate) role_offset: u64,
}

fn deserialize_presentation_geometry_index<'de, D: Deserializer<'de>>(
    deserializer: D,
) -> Result<NonZeroU32, D::Error> {
    NonZeroU32::new(u32::deserialize(deserializer)?)
        .ok_or_else(|| serde::de::Error::custom("geometry_record_index must be nonzero"))
}

/// Paired `EntityGenesis` dimension frame carrying annotation geometry.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    try_from = "DesignDimensionAnnotationFrameWire",
    into = "DesignDimensionAnnotationFrameWire"
)]
pub(crate) struct DesignDimensionAnnotationFrame {
    /// Globally unique deterministic identifier for this native record.
    pub(crate) id: String,
    /// Companion record containing this frame, absent before the first companion in a scope.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) companion_record_index: Option<u32>,
    /// Companion record of the dimension parameter governed by this frame.
    pub(crate) governing_companion_record_index: u32,
    /// Byte offset of the primary indexed record header.
    byte_offset: u64,
    /// Source per-file dynamic three-digit ASCII class tag.
    class_tag: DesignClassTag,
    /// Source indexed-record identity.
    pub(crate) record_index: u32,
    /// Byte length from the primary through the paired header boundary.
    frame_length: u64,
    /// Ordered nullable locus operands.
    operands: Vec<DesignDimensionAnnotationLocus>,
    /// `EntityGenesis` origin bitfield.
    pub(crate) entity_genesis: u64,
    /// Opaque annotation bytes between the genesis block and governing owner.
    annotation_bytes: Vec<u8>,
    /// Indexed parameter-owner record selecting the governed dimension.
    pub(crate) governing_owner_record_index: u32,
    /// Ordered non-null return geometry records.
    return_members: Vec<NonZeroU32>,
    /// Dynamic class tag of the paired indexed record.
    paired_class_tag: DesignClassTag,
    /// Numeric design-entity suffix of the owning sketch.
    pub(crate) owner_reference: u32,
}

/// Nullable annotation geometry and its dimension role.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct DesignDimensionAnnotationLocus {
    /// Indexed sketch geometry record, absent for the null locus.
    pub(crate) geometry_record_index: Option<NonZeroU32>,
    /// Source dimension-role code.
    pub(crate) role: u32,
}

/// Unchecked annotation frame payload and offsets.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct DesignDimensionAnnotationFrameDraft {
    /// Globally unique deterministic identifier for this native record.
    pub(crate) id: String,
    /// Companion record containing this frame, absent before the first companion in a scope.
    pub(crate) companion_record_index: Option<u32>,
    /// Companion record of the dimension parameter governed by this frame.
    pub(crate) governing_companion_record_index: u32,
    /// Byte offset of the primary indexed record header.
    pub(crate) byte_offset: u64,
    /// Source per-file dynamic three-digit ASCII class tag.
    pub(crate) class_tag: DesignClassTag,
    /// Source indexed-record identity.
    pub(crate) record_index: u32,
    /// Byte length from the primary through the paired header boundary.
    pub(crate) frame_length: u64,
    /// Ordered nullable locus operands.
    pub(crate) operands: Vec<DesignDimensionAnnotationOperand>,
    /// `EntityGenesis` origin bitfield.
    pub(crate) entity_genesis: u64,
    /// Opaque annotation bytes between the genesis block and governing owner.
    pub(crate) annotation_bytes: Vec<u8>,
    /// Byte offset of `annotation_bytes`.
    pub(crate) annotation_byte_offset: u64,
    /// Indexed parameter-owner record selecting the governed dimension.
    pub(crate) governing_owner_record_index: u32,
    /// Byte offset of `governing_owner_record_index`.
    pub(crate) governing_owner_reference_offset: u64,
    /// Ordered non-null return geometry records.
    pub(crate) return_members: Vec<Located<NonZeroU32>>,
    /// Dynamic class tag of the paired indexed record.
    pub(crate) paired_class_tag: DesignClassTag,
    /// Byte offset of the paired indexed record header.
    pub(crate) paired_byte_offset: u64,
    /// Numeric design-entity suffix of the owning sketch.
    pub(crate) owner_reference: u32,
    /// Byte offset of `owner_reference`.
    pub(crate) owner_reference_offset: u64,
}

impl DesignDimensionAnnotationFrame {
    /// Admit an annotation frame with representable offsets and matching operand runs.
    pub(crate) fn try_new(draft: DesignDimensionAnnotationFrameDraft) -> Result<Self, String> {
        if draft.operands.is_empty() {
            return Err("operands must not be empty".into());
        }
        let operand_bytes = u64::try_from(draft.operands.len())
            .ok()
            .and_then(|count| count.checked_mul(15))
            .ok_or("operands length overflows frame offsets")?;
        let annotation_byte_offset = draft
            .byte_offset
            .checked_add(24)
            .and_then(|offset| offset.checked_add(operand_bytes))
            .and_then(|offset| offset.checked_add(57))
            .ok_or("annotation_byte_offset overflows")?;
        let governing_owner_reference_offset = u64::try_from(draft.annotation_bytes.len())
            .ok()
            .and_then(|len| annotation_byte_offset.checked_add(len))
            .and_then(|offset| offset.checked_add(1))
            .ok_or("governing_owner_reference_offset overflows")?;
        let paired_byte_offset = draft
            .byte_offset
            .checked_add(draft.frame_length)
            .ok_or("paired_byte_offset overflows")?;
        let owner_reference_offset = paired_byte_offset
            .checked_add(20)
            .ok_or("owner_reference_offset overflows")?;
        if draft.annotation_byte_offset != annotation_byte_offset {
            return Err("annotation_byte_offset disagrees with frame layout".into());
        }
        if draft.governing_owner_reference_offset != governing_owner_reference_offset {
            return Err("governing_owner_reference_offset disagrees with frame layout".into());
        }
        if draft.paired_byte_offset != paired_byte_offset {
            return Err("paired_byte_offset disagrees with frame layout".into());
        }
        if draft.owner_reference_offset != owner_reference_offset {
            return Err("owner_reference_offset disagrees with frame layout".into());
        }
        for (ordinal, operand) in draft.operands.iter().enumerate() {
            let start = draft.byte_offset + 24 + ordinal as u64 * 15;
            if operand.geometry_reference_offset != start + 1 || operand.role_offset != start + 11 {
                return Err(
                    "operands geometry_reference_offset or role_offset disagrees with frame layout"
                        .into(),
                );
            }
        }
        for (ordinal, member) in draft.return_members.iter().enumerate() {
            let expected = u64::try_from(ordinal)
                .ok()
                .and_then(|ordinal| ordinal.checked_mul(11))
                .and_then(|delta| governing_owner_reference_offset.checked_add(delta))
                .and_then(|offset| offset.checked_add(15))
                .ok_or("return_member_offsets overflow")?;
            if member.offset != expected {
                return Err("return_member_offsets disagree with frame layout".into());
            }
        }
        let mut operand_members = draft
            .operands
            .iter()
            .filter_map(|operand| operand.geometry_record_index)
            .collect::<Vec<_>>();
        let mut return_members = draft
            .return_members
            .iter()
            .map(|member| member.value)
            .collect::<Vec<_>>();
        operand_members.sort_unstable();
        return_members.sort_unstable();
        if operand_members != return_members {
            return Err("return_members disagree with operands geometry indices".into());
        }
        Ok(Self {
            id: draft.id,
            companion_record_index: draft.companion_record_index,
            governing_companion_record_index: draft.governing_companion_record_index,
            byte_offset: draft.byte_offset,
            class_tag: draft.class_tag,
            record_index: draft.record_index,
            frame_length: draft.frame_length,
            operands: draft
                .operands
                .into_iter()
                .map(|operand| DesignDimensionAnnotationLocus {
                    geometry_record_index: operand.geometry_record_index,
                    role: operand.role,
                })
                .collect(),
            entity_genesis: draft.entity_genesis,
            annotation_bytes: draft.annotation_bytes,
            governing_owner_record_index: draft.governing_owner_record_index,
            return_members: draft
                .return_members
                .into_iter()
                .map(|member| member.value)
                .collect(),
            paired_class_tag: draft.paired_class_tag,
            owner_reference: draft.owner_reference,
        })
    }

    /// Retained byte offset.
    pub(crate) fn byte_offset(&self) -> u64 {
        self.byte_offset
    }

    /// Retained operands.
    pub(crate) fn operands(&self) -> &[DesignDimensionAnnotationLocus] {
        &self.operands
    }

    /// Derived annotation byte offset.
    pub(crate) fn annotation_byte_offset(&self) -> u64 {
        self.byte_offset + 24 + self.operands.len() as u64 * 15 + 57
    }

    /// Derived governing owner reference offset.
    fn governing_owner_reference_offset(&self) -> u64 {
        self.annotation_byte_offset() + self.annotation_bytes.len() as u64 + 1
    }

    /// Derived paired byte offset.
    pub(crate) fn paired_byte_offset(&self) -> u64 {
        self.byte_offset + self.frame_length
    }

    /// Derived owner reference offset.
    pub(super) fn owner_reference_offset(&self) -> u64 {
        self.paired_byte_offset() + 20
    }

    /// Recover the payload with its derived offsets.
    pub(crate) fn into_draft(self) -> DesignDimensionAnnotationFrameDraft {
        let annotation_byte_offset = self.annotation_byte_offset();
        let governing_owner_reference_offset = self.governing_owner_reference_offset();
        let paired_byte_offset = self.paired_byte_offset();
        let owner_reference_offset = self.owner_reference_offset();
        DesignDimensionAnnotationFrameDraft {
            id: self.id,
            companion_record_index: self.companion_record_index,
            governing_companion_record_index: self.governing_companion_record_index,
            byte_offset: self.byte_offset,
            class_tag: self.class_tag,
            record_index: self.record_index,
            frame_length: self.frame_length,
            operands: self
                .operands
                .into_iter()
                .enumerate()
                .map(|(ordinal, operand)| DesignDimensionAnnotationOperand {
                    geometry_record_index: operand.geometry_record_index,
                    role: operand.role,
                    geometry_reference_offset: self.byte_offset + 25 + ordinal as u64 * 15,
                    role_offset: self.byte_offset + 35 + ordinal as u64 * 15,
                })
                .collect(),
            entity_genesis: self.entity_genesis,
            annotation_bytes: self.annotation_bytes,
            annotation_byte_offset,
            governing_owner_record_index: self.governing_owner_record_index,
            governing_owner_reference_offset,
            return_members: self
                .return_members
                .into_iter()
                .enumerate()
                .map(|(ordinal, value)| Located {
                    value,
                    offset: governing_owner_reference_offset + 15 + ordinal as u64 * 11,
                })
                .collect(),
            paired_class_tag: self.paired_class_tag,
            paired_byte_offset,
            owner_reference: self.owner_reference,
            owner_reference_offset,
        }
    }
}

/// Paired `EntityGenesis` dimension frame carrying annotation geometry.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct DesignDimensionAnnotationFrameWire {
    /// Globally unique deterministic identifier for this native record.
    id: String,
    /// Companion record containing this frame, absent before the first companion in a scope.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_companion_record_index"
    )]
    companion_record_index: Option<u32>,
    /// Companion record of the dimension parameter governed by this frame.
    governing_companion_record_index: u32,
    /// Byte offset of the primary indexed record header.
    byte_offset: u64,
    /// Source per-file dynamic three-digit ASCII class tag.
    class_tag: String,
    /// Source indexed-record identity.
    record_index: u32,
    /// Byte length from the primary through the paired header boundary.
    frame_length: u64,
    /// Ordered nullable locus operands.
    operands: Vec<DesignDimensionAnnotationOperand>,
    /// `EntityGenesis` origin bitfield.
    entity_genesis: u64,
    /// Opaque annotation bytes between the genesis block and governing owner.
    annotation_bytes: Vec<u8>,
    /// Byte offset of `annotation_bytes`.
    annotation_byte_offset: u64,
    /// Indexed parameter-owner record selecting the governed dimension.
    governing_owner_record_index: u32,
    /// Byte offset of `governing_owner_record_index`.
    governing_owner_reference_offset: u64,
    /// Ordered non-null return geometry records.
    return_members: Vec<u32>,
    /// Byte offsets parallel to `return_members`.
    return_member_offsets: Vec<u64>,
    /// Dynamic class tag of the paired indexed record.
    paired_class_tag: String,
    /// Byte offset of the paired indexed record header.
    paired_byte_offset: u64,
    /// Numeric design-entity suffix of the owning sketch.
    owner_reference: u32,
    /// Byte offset of `owner_reference`.
    owner_reference_offset: u64,
}

impl TryFrom<DesignDimensionAnnotationFrameWire> for DesignDimensionAnnotationFrame {
    type Error = String;
    fn try_from(wire: DesignDimensionAnnotationFrameWire) -> Result<Self, Self::Error> {
        if wire.return_members.len() != wire.return_member_offsets.len() {
            return Err("return_members and return_member_offsets must have equal lengths".into());
        }
        Self::try_new(DesignDimensionAnnotationFrameDraft {
            return_members: wire
                .return_members
                .into_iter()
                .zip(wire.return_member_offsets)
                .map(|(value, offset)| {
                    let value = NonZeroU32::new(value)
                        .ok_or("return_members must contain nonzero geometry indices")?;
                    Ok(Located { value, offset })
                })
                .collect::<Result<_, Self::Error>>()?,
            id: wire.id,
            companion_record_index: wire.companion_record_index,
            governing_companion_record_index: wire.governing_companion_record_index,
            byte_offset: wire.byte_offset,
            class_tag: wire.class_tag.try_into()?,
            record_index: wire.record_index,
            frame_length: wire.frame_length,
            operands: wire.operands,
            entity_genesis: wire.entity_genesis,
            annotation_bytes: wire.annotation_bytes,
            annotation_byte_offset: wire.annotation_byte_offset,
            governing_owner_record_index: wire.governing_owner_record_index,
            governing_owner_reference_offset: wire.governing_owner_reference_offset,
            paired_class_tag: wire.paired_class_tag.try_into()?,
            paired_byte_offset: wire.paired_byte_offset,
            owner_reference: wire.owner_reference,
            owner_reference_offset: wire.owner_reference_offset,
        })
    }
}

impl From<DesignDimensionAnnotationFrame> for DesignDimensionAnnotationFrameWire {
    fn from(value: DesignDimensionAnnotationFrame) -> Self {
        let value = value.into_draft();
        let (return_members, return_member_offsets) = value
            .return_members
            .into_iter()
            .map(|member| (member.value.get(), member.offset))
            .unzip();
        Self {
            return_members,
            return_member_offsets,
            id: value.id,
            companion_record_index: value.companion_record_index,
            governing_companion_record_index: value.governing_companion_record_index,
            byte_offset: value.byte_offset,
            class_tag: value.class_tag.into(),
            record_index: value.record_index,
            frame_length: value.frame_length,
            operands: value.operands,
            entity_genesis: value.entity_genesis,
            annotation_bytes: value.annotation_bytes,
            annotation_byte_offset: value.annotation_byte_offset,
            governing_owner_record_index: value.governing_owner_record_index,
            governing_owner_reference_offset: value.governing_owner_reference_offset,
            paired_class_tag: value.paired_class_tag.into(),
            paired_byte_offset: value.paired_byte_offset,
            owner_reference: value.owner_reference,
            owner_reference_offset: value.owner_reference_offset,
        }
    }
}

/// Paired Fusion presentation frame that directly identifies a dimension's
/// measured sketch geometry.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) struct DesignDimensionPresentationFrame {
    /// Globally unique deterministic identifier for this native record.
    pub(crate) id: String,
    /// Byte offset of the primary indexed record header.
    pub(crate) byte_offset: u64,
    /// Source per-file dynamic three-digit ASCII class tag.
    pub(crate) class_tag: DesignClassTag,
    /// Source indexed-record identity.
    pub(crate) record_index: u32,
    /// Byte length from the primary through the paired-header boundary.
    pub(crate) frame_length: u64,
    /// Ordered typed sketch-geometry operands.
    pub(crate) operands: Vec<DesignDimensionPresentationOperand>,
    /// Opaque presentation bytes between the operand run and the paired
    /// `EntityTracking` header.
    pub(crate) presentation_bytes: Vec<u8>,
    /// Byte offset of `presentation_bytes`.
    pub(crate) presentation_byte_offset: u64,
    /// Dynamic class tag of the paired `EntityTracking` header.
    pub(crate) paired_class_tag: DesignClassTag,
    /// Byte offset of the paired indexed record header.
    pub(crate) paired_byte_offset: u64,
    /// Numeric suffix of the owning Sketch entity.
    pub(crate) owner_reference: u32,
    /// Byte offset of `owner_reference`.
    pub(crate) owner_reference_offset: u64,
    /// Indexed parameter-owner record governed by this frame.
    pub(crate) governing_owner_record_index: u32,
    /// Indexed Design parameter selected by the governing owner.
    pub(crate) governing_parameter_record_index: u32,
    /// Indexed parameter companion selected by the governing owner.
    pub(crate) governing_companion_record_index: u32,
}

/// One typed geometry locus and its dimension-role code.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct DesignDimensionLocus {
    /// Return reference at the same position in the return run.
    pub(crate) returned: Located<u32>,
    /// Indexed sketch-point or sketch-curve record.
    pub(crate) geometry_record_index: u32,
    /// Byte offset of `geometry_record_index`.
    pub(crate) geometry_reference_offset: u64,
    /// Source role code following the geometry reference.
    pub(crate) role: u32,
    /// Byte offset of `role`.
    pub(crate) role_offset: u64,
}

/// Counted-locus frame nested under a dimensional parameter companion.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    try_from = "DesignDimensionLocusGroupWire",
    into = "DesignDimensionLocusGroupWire"
)]
pub(crate) struct DesignDimensionLocusGroup {
    /// Globally unique deterministic identifier for this native record.
    pub(crate) id: String,
    /// Companion record containing this frame.
    pub(crate) companion_record_index: u32,
    /// Byte offset of the indexed record header.
    pub(crate) byte_offset: u64,
    /// Source per-file dynamic three-digit ASCII class tag.
    pub(crate) class_tag: DesignClassTag,
    /// Source indexed-record identity.
    pub(crate) record_index: u32,
    /// Byte length through the zero byte preceding the next indexed header.
    pub(crate) frame_length: u64,
    /// Ordered typed geometry loci.
    pub(crate) loci: Vec<DesignDimensionLocus>,
    /// Numeric design-entity suffix of the owning sketch.
    pub(crate) owner_reference: u32,
    /// Byte offset of `owner_reference`.
    pub(crate) owner_reference_offset: u64,
    /// Source role code following the owner reference.
    pub(crate) owner_role: u32,
    /// Byte offset of `owner_role`.
    pub(crate) owner_role_offset: u64,
    /// Source constraint-state mask.
    pub(crate) state: u32,
    /// Byte offset of `state`.
    pub(crate) state_offset: u64,
    /// Dynamic class tag of the immediately following indexed record.
    pub(crate) next_class_tag: DesignClassTag,
    /// Identity of the immediately following indexed record.
    pub(crate) next_record_index: u32,
    /// Byte offset of the immediately following indexed record.
    pub(crate) next_byte_offset: u64,
}

/// One typed geometry locus and its dimension-role code.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct DesignDimensionLocusWire {
    /// Indexed sketch-point or sketch-curve record.
    geometry_record_index: u32,
    /// Byte offset of `geometry_record_index`.
    geometry_reference_offset: u64,
    /// Source role code following the geometry reference.
    role: u32,
    /// Byte offset of `role`.
    role_offset: u64,
}

/// Counted-locus frame nested under a dimensional parameter companion.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct DesignDimensionLocusGroupWire {
    /// Globally unique deterministic identifier for this native record.
    id: String,
    /// Companion record containing this frame.
    companion_record_index: u32,
    /// Byte offset of the indexed record header.
    byte_offset: u64,
    /// Source per-file dynamic three-digit ASCII class tag.
    class_tag: String,
    /// Source indexed-record identity.
    record_index: u32,
    /// Byte length through the zero byte preceding the next indexed header.
    frame_length: u64,
    /// Ordered typed geometry loci.
    loci: Vec<DesignDimensionLocusWire>,
    /// Numeric design-entity suffix of the owning sketch.
    owner_reference: u32,
    /// Byte offset of `owner_reference`.
    owner_reference_offset: u64,
    /// Source role code following the owner reference.
    owner_role: u32,
    /// Byte offset of `owner_role`.
    owner_role_offset: u64,
    /// Source constraint-state mask.
    state: u32,
    /// Byte offset of `state`.
    state_offset: u64,
    /// Constraint kinds selected by `state`.
    constraint_kinds: Vec<SketchConstraintKind>,
    /// Bits in `state` outside the defined constraint mask.
    unknown_constraint_bits: u32,
    /// Ordered return geometry records.
    return_members: Vec<u32>,
    /// Byte offsets parallel to `return_members`.
    return_member_offsets: Vec<u64>,
    /// Dynamic class tag of the immediately following indexed record.
    next_class_tag: String,
    /// Identity of the immediately following indexed record.
    next_record_index: u32,
    /// Byte offset of the immediately following indexed record.
    next_byte_offset: u64,
}

impl DesignDimensionLocusGroup {
    /// Constraint kinds selected by the owner mask.
    #[must_use]
    pub(crate) fn owner_kinds(&self) -> Vec<SketchConstraintKind> {
        constraint_kinds_from_state(u64::from(self.owner_role)).0
    }

    #[must_use]
    fn constraint_kinds(&self) -> Vec<SketchConstraintKind> {
        constraint_kinds_from_state(u64::from(self.state)).0
    }

    #[must_use]
    fn unknown_constraint_bits(&self) -> u32 {
        self.state & !(SKETCH_CONSTRAINT_MASK as u32)
    }
}

impl TryFrom<DesignDimensionLocusGroupWire> for DesignDimensionLocusGroup {
    type Error = String;
    fn try_from(wire: DesignDimensionLocusGroupWire) -> Result<Self, Self::Error> {
        if wire.return_members.len() != wire.loci.len() {
            return Err("return_members must match loci".into());
        }
        if wire.return_member_offsets.len() != wire.loci.len() {
            return Err("return_member_offsets must match loci".into());
        }
        let (kinds, unknown) = constraint_kinds_from_state(u64::from(wire.state));
        if wire.constraint_kinds != kinds {
            return Err("constraint_kinds must match state".into());
        }
        if u64::from(wire.unknown_constraint_bits) != unknown {
            return Err("unknown_constraint_bits must match state".into());
        }
        let loci = wire
            .loci
            .into_iter()
            .zip(
                wire.return_members
                    .into_iter()
                    .zip(wire.return_member_offsets),
            )
            .map(|(locus, (value, offset))| DesignDimensionLocus {
                geometry_record_index: locus.geometry_record_index,
                geometry_reference_offset: locus.geometry_reference_offset,
                role: locus.role,
                role_offset: locus.role_offset,
                returned: Located { value, offset },
            })
            .collect();
        Ok(Self {
            loci,
            id: wire.id,
            companion_record_index: wire.companion_record_index,
            byte_offset: wire.byte_offset,
            class_tag: wire.class_tag.try_into()?,
            record_index: wire.record_index,
            frame_length: wire.frame_length,
            owner_reference: wire.owner_reference,
            owner_reference_offset: wire.owner_reference_offset,
            owner_role: wire.owner_role,
            owner_role_offset: wire.owner_role_offset,
            state: wire.state,
            state_offset: wire.state_offset,
            next_class_tag: wire.next_class_tag.try_into()?,
            next_record_index: wire.next_record_index,
            next_byte_offset: wire.next_byte_offset,
        })
    }
}

impl From<DesignDimensionLocusGroup> for DesignDimensionLocusGroupWire {
    // Output cardinalities are bounded by already-materialized input vectors.
    #[allow(clippy::disallowed_methods)]
    fn from(value: DesignDimensionLocusGroup) -> Self {
        let constraint_kinds = value.constraint_kinds();
        let unknown_constraint_bits = value.unknown_constraint_bits();
        let mut loci = Vec::with_capacity(value.loci.len());
        let mut return_members = Vec::with_capacity(value.loci.len());
        let mut return_member_offsets = Vec::with_capacity(value.loci.len());
        for locus in value.loci {
            return_members.push(locus.returned.value);
            return_member_offsets.push(locus.returned.offset);
            loci.push(DesignDimensionLocusWire {
                geometry_record_index: locus.geometry_record_index,
                geometry_reference_offset: locus.geometry_reference_offset,
                role: locus.role,
                role_offset: locus.role_offset,
            });
        }
        Self {
            loci,
            return_members,
            return_member_offsets,
            constraint_kinds,
            unknown_constraint_bits,
            id: value.id,
            companion_record_index: value.companion_record_index,
            byte_offset: value.byte_offset,
            class_tag: value.class_tag.into(),
            record_index: value.record_index,
            frame_length: value.frame_length,
            owner_reference: value.owner_reference,
            owner_reference_offset: value.owner_reference_offset,
            owner_role: value.owner_role,
            owner_role_offset: value.owner_role_offset,
            state: value.state,
            state_offset: value.state_offset,
            next_class_tag: value.next_class_tag.into(),
            next_record_index: value.next_record_index,
            next_byte_offset: value.next_byte_offset,
        }
    }
}
