disallowed-methods = [
  "alloc::vec::Vec::with_capacity",
  "alloc::vec::Vec::reserve",
  "alloc::vec::Vec::reserve_exact",
  "alloc::vec::Vec::resize",
  "alloc::vec::Vec::resize_with",
  "core::iter::repeat_n",
]
