// SPDX-License-Identifier: Apache-2.0
//! Encoder tests over the canonical unit cube.
//!
//! The emitted program cannot be executed here — running it needs a Python
//! interpreter with build123d installed — so these assert on the properties
//! that make the program correct: that every face is emitted, that the carriers
//! and boundaries are the ones the IR carries, and that the output is
//! deterministic.

use cadmpeg_codec_build123d::{Build123dEncoder, FORMAT_ID};
use cadmpeg_ir::codec::{EncodeInput, Encoder};
use cadmpeg_ir::examples::unit_cube;
use cadmpeg_ir::report::Severity;

fn emit(ir: &cadmpeg_ir::document::CadIr) -> (String, cadmpeg_ir::report::ExportReport) {
    let plan = Build123dEncoder
        .plan(EncodeInput { ir, fidelity: None })
        .expect("the unit cube plans without error");
    let report = plan.report().clone();
    let mut bytes = Vec::new();
    plan.write_to(&mut bytes).expect("the plan writes");
    (
        String::from_utf8(bytes).expect("the program is UTF-8"),
        report,
    )
}

#[test]
fn every_cube_face_is_emitted() {
    let ir = unit_cube();
    let (source, report) = emit(&ir);
    assert_eq!(report.format, FORMAT_ID);
    assert_eq!(report.census.counts.get("faces"), Some(&6));
    assert_eq!(report.census.counts.get("faces_planar"), Some(&6));
    assert_eq!(source.matches("faces.append").count(), 6);
}

#[test]
fn the_cube_emits_no_losses() {
    let ir = unit_cube();
    let (_, report) = emit(&ir);
    assert!(
        report.losses.is_empty(),
        "a fully analytic solid should export without loss, got {:?}",
        report.losses
    );
    assert_eq!(report.error_count(), 0);
}

#[test]
fn the_program_is_runnable_python() {
    let ir = unit_cube();
    let (source, _) = emit(&ir);
    assert!(source.starts_with("\"\"\"build123d program generated by cadmpeg."));
    assert!(source.contains("from build123d import *"));
    // Every face is guarded, so one refused face cannot abort the program.
    assert_eq!(
        source.matches("try:").count(),
        source.matches("except Exception as error:").count()
    );
    // The epilogue always defines a result and reports a volume.
    assert!(source.contains("print(\"volume: %.6f\""));
}

#[test]
fn cube_geometry_reaches_the_program() {
    let ir = unit_cube();
    let (source, _) = emit(&ir);
    // The cube spans 0..10 on each axis, so its corners must appear verbatim
    // rather than as rounded machine output.
    assert!(source.contains("(10, 10, 10)"), "{source}");
    assert!(source.contains("(0, 0, 0)"), "{source}");
    // Whole numbers stay whole: a coordinate that reads as machine output is a
    // sign the formatter has drifted.
    for line in source
        .lines()
        .filter(|line| line.contains("Edge.make_line"))
    {
        assert!(
            !line.contains("e-") && !line.contains("e+"),
            "coordinates should not carry exponent notation: {line}"
        );
    }
}

#[test]
fn emission_is_deterministic() {
    let ir = unit_cube();
    let (first, _) = emit(&ir);
    let (second, _) = emit(&ir);
    assert_eq!(first, second);
}

#[test]
fn losses_are_machine_readable_when_a_carrier_is_unsupported() {
    let mut ir = unit_cube();
    // Replace one carrier with a family this encoder does not rebuild.
    let surface = ir
        .model
        .surfaces
        .first_mut()
        .expect("the cube has carriers");
    surface.geometry = cadmpeg_ir::geometry::SurfaceGeometry::Unknown { record: None };
    let (_, report) = emit(&ir);
    assert!(
        report
            .losses
            .iter()
            .any(|loss| loss.severity >= Severity::Warning),
        "an unsupported carrier must surface as loss"
    );
}
