// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// Unit tests compare this registry-owned list with the codec-owned enum.

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 2] = [
    DialectId::pinned("inventor:cfb3-rse31-meta8"),
    DialectId::pinned("inventor:unknown"),
];
