// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// The generated row array is checked as an artifact, not read at runtime.
#![allow(dead_code)]

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const CFB3_RSE31_META8_STR: &str = "inventor:cfb3-rse31-meta8";
#[rustfmt::skip]
pub(super) const CFB3_RSE31_META8: DialectId = DialectId::pinned(CFB3_RSE31_META8_STR);
#[rustfmt::skip]
pub(super) const UNKNOWN_STR: &str = "inventor:unknown";
#[rustfmt::skip]
pub(super) const UNKNOWN: DialectId = DialectId::pinned(UNKNOWN_STR);

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 2] = [
    CFB3_RSE31_META8,
    UNKNOWN,
];
