// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/check-dialects.py from docs/dialects.toml.
// Do not edit this file directly.

/// Registry-owned format namespace.
pub(crate) const FORMAT: &str = "inventor";

/// Registry-owned dialect id `inventor:cfb3-rse31-meta8`.
pub(crate) const INVENTOR_CFB3_RSE31_META8: DialectId = cadmpeg_core::dialect_id!("inventor:cfb3-rse31-meta8");
/// Registry-owned dialect id `inventor:unknown`.
pub(crate) const INVENTOR_UNKNOWN: DialectId = cadmpeg_core::dialect_id!("inventor:unknown");
