// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// The generated row array is checked as an artifact, not read at runtime.
#![allow(dead_code)]

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const MANIFEST_3_2_0_0_STR: &str = "f3d:manifest-3-2-0-0";
#[rustfmt::skip]
pub(super) const MANIFEST_3_2_0_0: DialectId = DialectId::pinned(MANIFEST_3_2_0_0_STR);
#[rustfmt::skip]
pub(super) const F3Z_MULTI_DOCUMENT_STR: &str = "f3d:f3z-multi-document";
#[rustfmt::skip]
pub(super) const F3Z_MULTI_DOCUMENT: DialectId = DialectId::pinned(F3Z_MULTI_DOCUMENT_STR);
#[rustfmt::skip]
pub(super) const UNKNOWN_STR: &str = "f3d:unknown";
#[rustfmt::skip]
pub(super) const UNKNOWN: DialectId = DialectId::pinned(UNKNOWN_STR);

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 3] = [
    MANIFEST_3_2_0_0,
    F3Z_MULTI_DOCUMENT,
    UNKNOWN,
];
