// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/check-dialects.py from docs/dialects.toml.
// Do not edit this file directly.

/// Registry-owned format namespace.
pub(crate) const FORMAT: &str = "f3d";

/// Registry-owned dialect id `f3d:manifest-3-2-0-0`.
pub(crate) const F3D_MANIFEST_3_2_0_0: DialectId = DialectId::pinned("f3d:manifest-3-2-0-0");
/// Registry-owned dialect id `f3d:f3z-multi-document`.
pub(crate) const F3D_F3Z_MULTI_DOCUMENT: DialectId = DialectId::pinned("f3d:f3z-multi-document");
/// Registry-owned dialect id `f3d:unknown`.
pub(crate) const F3D_UNKNOWN: DialectId = DialectId::pinned("f3d:unknown");
