// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// The generated row array is checked as an artifact, not read at runtime.
#![allow(dead_code)]

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const DEPDB_STR: &str = "creo:depdb";
#[rustfmt::skip]
pub(super) const DEPDB: DialectId = DialectId::pinned(DEPDB_STR);
#[rustfmt::skip]
pub(super) const ND_STR: &str = "creo:nd";
#[rustfmt::skip]
pub(super) const ND: DialectId = DialectId::pinned(ND_STR);
#[rustfmt::skip]
pub(super) const LEGACY_ASCII_STR: &str = "creo:legacy-ascii";
#[rustfmt::skip]
pub(super) const LEGACY_ASCII: DialectId = DialectId::pinned(LEGACY_ASCII_STR);
#[rustfmt::skip]
pub(super) const UNKNOWN_STR: &str = "creo:unknown";
#[rustfmt::skip]
pub(super) const UNKNOWN: DialectId = DialectId::pinned(UNKNOWN_STR);

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 4] = [
    DEPDB,
    ND,
    LEGACY_ASCII,
    UNKNOWN,
];
