// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/check-dialects.py from docs/dialects.toml.
// Do not edit this file directly.

/// Registry-owned format namespace.
pub(crate) const FORMAT: &str = "creo";

/// Registry-owned dialect id `creo:depdb`.
pub(crate) const CREO_DEPDB: DialectId = DialectId::pinned("creo:depdb");
/// Registry-owned dialect id `creo:nd`.
pub(crate) const CREO_ND: DialectId = DialectId::pinned("creo:nd");
/// Registry-owned dialect id `creo:legacy-ascii`.
pub(crate) const CREO_LEGACY_ASCII: DialectId = DialectId::pinned("creo:legacy-ascii");
/// Registry-owned dialect id `creo:unknown`.
pub(crate) const CREO_UNKNOWN: DialectId = DialectId::pinned("creo:unknown");
