// SPDX-License-Identifier: Apache-2.0
//! Stable loss vocabulary for IGES decoding and writing.
//!
//! Every fallback, approximation, and drop the codec reports carries a stable
//! machine-readable code from [`IgesLossCode`]. Codes are the gating surface:
//! harness oracles and downstream tooling key on them, never on the
//! human-readable message text, so a reworded message is not a contract change
//! and a new drop path without a code does not compile.
//!
//! [`IgesLossCode::note`] is the single construction path for a
//! [`LossNote`] in this crate: it fixes the shared loss category and the
//! severity from the code so the two cannot drift apart across sites, and it
//! leaves only the per-instance message to the caller. Local codes appear on
//! [`LossNote::code`] under the `iges` namespace.
//!
//! [`IgesLossCode::shared_taxonomy`] is an exhaustive match with no fall-through
//! arm. A default arm would silently assign a category to a code added later,
//! and the categories this codec spans (decode, entity, graph, presentation,
//! geometry, writer) have no honest common default.

use cadmpeg_ir::report::{LossKind, LossNote, LossTaxonomy, Severity};

/// A stable, machine-readable identifier for one IGES transfer loss.
///
/// Variants are grouped by the record family whose transfer degraded. The
/// string form (via [`IgesLossCode::code`]) is the stable contract.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum IgesLossCode {
    /// Product-occurrence expansion stopped at the configured output limit.
    OccurrenceExpansionOutputTruncated,
    /// Product-occurrence expansion stopped at the configured nesting-depth limit.
    OccurrenceExpansionDepthTruncated,
    /// Product-occurrence root inference was suppressed by a malformed member list.
    OccurrenceRootInferenceBlocked,
    /// Product-occurrence expansion omitted an instance or member with malformed placement data.
    OccurrencePlacementMalformed,
    /// An envelope-admitted entity was retained without a neutral projection.
    EntityRetainedUnprojected,
    /// An entity type/form is outside the Fixed ASCII mechanical/document envelope.
    EntityOutsideEnvelope,
    /// An entity was not projected; the instance message names the reason.
    EntityNotProjected,
    /// A boundary pcurve leaves the finite parameter domain of its support surface.
    BoundaryPcurveOutsideSupportDomain,
    /// A Directory Entry pointer did not resolve to the expected target.
    PointerUnresolved,
    /// Parameter Data has more than one structural trailing pointer-group boundary.
    ParameterBoundaryAmbiguous,
    /// Directory display, font, or color data was not projected.
    DisplayDataNotProjected,
    /// A drawing has conflicting valid properties of the same form.
    DrawingPropertyAmbiguous,
    /// The Global line-weight scale is unavailable, so no entity has a width.
    LineWeightScaleUnavailable,
    /// A Type 118 developability flag was not transferred to neutral geometry.
    RuledDevelopabilityNotTransferred,
    /// Type 112 or Type 114 header semantics were not transferred to neutral geometry.
    SplineHeaderNotTransferred,
    /// A Type 102 composite has no admitted concatenated carrier.
    CompositeCarrierDegraded,
    /// A Global metadata field is absent or malformed and was not transferred.
    GlobalMetadataFieldUnusable,
    /// A Global comparison context came from this codec's specification.
    GlobalSemanticContextSubstituted,
    /// The Global fields 13, 14, and 15 produced no millimetre length factor.
    GlobalLengthUnitUnresolved,
    /// The Global record is recoverable but departs from IGES 5.3 Table 1.
    GlobalNoncanonicalFraming,
    /// The declared Global specification version is outside the verified set.
    SourceDialectUnverified,
    /// Preserved source image required for a byte-exact write was unavailable.
    PreservedSourceUnavailable,
    /// Procedural definitions were reduced to writable solved carriers.
    ProceduralReduced,
    /// A native passthrough arena is not regenerated by the semantic writer.
    PassthroughRecordOmitted,
    /// The emitted Global minimum resolution exceeds the neutral declaration.
    WriterMinimumResolutionAdjusted,
}

impl IgesLossCode {
    /// Every code, in declaration order.
    #[cfg(test)]
    pub const ALL: &'static [IgesLossCode] = &[
        Self::OccurrenceExpansionOutputTruncated,
        Self::OccurrenceExpansionDepthTruncated,
        Self::OccurrenceRootInferenceBlocked,
        Self::OccurrencePlacementMalformed,
        Self::EntityRetainedUnprojected,
        Self::EntityOutsideEnvelope,
        Self::EntityNotProjected,
        Self::BoundaryPcurveOutsideSupportDomain,
        Self::PointerUnresolved,
        Self::ParameterBoundaryAmbiguous,
        Self::DisplayDataNotProjected,
        Self::DrawingPropertyAmbiguous,
        Self::LineWeightScaleUnavailable,
        Self::RuledDevelopabilityNotTransferred,
        Self::SplineHeaderNotTransferred,
        Self::CompositeCarrierDegraded,
        Self::GlobalMetadataFieldUnusable,
        Self::GlobalSemanticContextSubstituted,
        Self::GlobalLengthUnitUnresolved,
        Self::GlobalNoncanonicalFraming,
        Self::SourceDialectUnverified,
        Self::PreservedSourceUnavailable,
        Self::ProceduralReduced,
        Self::PassthroughRecordOmitted,
        Self::WriterMinimumResolutionAdjusted,
    ];

    /// The stable string identifier. This is the gating contract.
    #[must_use]
    pub const fn code(self) -> &'static str {
        match self {
            Self::OccurrenceExpansionOutputTruncated => "occurrence.expansion-output-truncated",
            Self::OccurrenceExpansionDepthTruncated => "occurrence.expansion-depth-truncated",
            Self::OccurrenceRootInferenceBlocked => "occurrence.root-inference-blocked",
            Self::OccurrencePlacementMalformed => "occurrence.placement-malformed",
            Self::EntityRetainedUnprojected => "entity.retained-unprojected",
            Self::EntityOutsideEnvelope => "entity.outside-envelope",
            Self::EntityNotProjected => "entity.not-projected",
            Self::BoundaryPcurveOutsideSupportDomain => {
                "topology.boundary-pcurve-outside-support-domain"
            }
            Self::PointerUnresolved => "graph.pointer-unresolved",
            Self::ParameterBoundaryAmbiguous => "parameter.boundary-ambiguous",
            Self::DisplayDataNotProjected => "presentation.display-data-not-projected",
            Self::DrawingPropertyAmbiguous => "presentation.drawing-property-ambiguous",
            Self::LineWeightScaleUnavailable => "presentation.line-weight-scale-unavailable",
            Self::RuledDevelopabilityNotTransferred => {
                "geometry.ruled-developability-not-transferred"
            }
            Self::SplineHeaderNotTransferred => "geometry.spline-header-not-transferred",
            Self::CompositeCarrierDegraded => "curve.composite-carrier-degraded",
            Self::GlobalMetadataFieldUnusable => "global.metadata-field-unusable",
            Self::GlobalSemanticContextSubstituted => "global.semantic-context-substituted",
            Self::GlobalLengthUnitUnresolved => "global.length-unit-unresolved",
            Self::GlobalNoncanonicalFraming => "global.noncanonical-framing",
            Self::SourceDialectUnverified => "source.dialect-unverified",
            Self::PreservedSourceUnavailable => "source.preserved-image-unavailable",
            Self::ProceduralReduced => "geometry.procedural-reduced",
            Self::PassthroughRecordOmitted => "writer.passthrough-omitted",
            Self::WriterMinimumResolutionAdjusted => "writer.minimum-resolution-adjusted",
        }
    }

    /// The severity of this loss.
    #[must_use]
    pub const fn severity(self) -> Severity {
        match self {
            Self::PreservedSourceUnavailable | Self::GlobalLengthUnitUnresolved => {
                Severity::Blocking
            }
            Self::ProceduralReduced => Severity::Info,
            Self::OccurrenceExpansionOutputTruncated
            | Self::OccurrenceExpansionDepthTruncated
            | Self::OccurrenceRootInferenceBlocked
            | Self::OccurrencePlacementMalformed
            | Self::EntityRetainedUnprojected
            | Self::EntityOutsideEnvelope
            | Self::EntityNotProjected
            | Self::BoundaryPcurveOutsideSupportDomain
            | Self::PointerUnresolved
            | Self::ParameterBoundaryAmbiguous
            | Self::DisplayDataNotProjected
            | Self::DrawingPropertyAmbiguous
            | Self::LineWeightScaleUnavailable
            | Self::RuledDevelopabilityNotTransferred
            | Self::SplineHeaderNotTransferred
            | Self::CompositeCarrierDegraded
            | Self::GlobalMetadataFieldUnusable
            | Self::GlobalSemanticContextSubstituted
            | Self::GlobalNoncanonicalFraming
            | Self::SourceDialectUnverified
            | Self::PassthroughRecordOmitted
            | Self::WriterMinimumResolutionAdjusted => Severity::Warning,
        }
    }

    /// The shared cross-codec category this loss reports under.
    const fn shared_taxonomy(self) -> LossTaxonomy {
        match self {
            Self::OccurrenceExpansionOutputTruncated
            | Self::OccurrenceExpansionDepthTruncated
            | Self::OccurrenceRootInferenceBlocked
            | Self::OccurrencePlacementMalformed => LossTaxonomy::DecodeDiagnostic,
            Self::EntityRetainedUnprojected
            | Self::EntityOutsideEnvelope
            | Self::EntityNotProjected => LossTaxonomy::RecordNotTyped,
            Self::BoundaryPcurveOutsideSupportDomain => LossTaxonomy::SourceTopologyInvalid,
            Self::PointerUnresolved => LossTaxonomy::ReferenceGraphNotClosed,
            Self::ParameterBoundaryAmbiguous => LossTaxonomy::DecodeDiagnostic,
            Self::DisplayDataNotProjected | Self::LineWeightScaleUnavailable => {
                LossTaxonomy::MaterialNotTransferred
            }
            Self::DrawingPropertyAmbiguous
            | Self::RuledDevelopabilityNotTransferred
            | Self::SplineHeaderNotTransferred
            | Self::GlobalMetadataFieldUnusable => LossTaxonomy::MetadataNotTransferred,
            Self::CompositeCarrierDegraded | Self::GlobalLengthUnitUnresolved => {
                LossTaxonomy::GeometryNotTransferred
            }
            Self::GlobalSemanticContextSubstituted | Self::GlobalNoncanonicalFraming => {
                LossTaxonomy::NoncanonicalSourceSyntax
            }
            Self::SourceDialectUnverified => LossTaxonomy::SourceDialectUnverified,
            Self::PreservedSourceUnavailable => LossTaxonomy::PreservedSourceUnavailable,
            Self::ProceduralReduced => LossTaxonomy::ProceduralReduced,
            Self::PassthroughRecordOmitted => LossTaxonomy::PassthroughRecordOmitted,
            Self::WriterMinimumResolutionAdjusted => LossTaxonomy::MetadataNotTransferred,
        }
    }

    /// Namespaced [`LossKind`] for this local code, classified by taxonomy.
    #[must_use]
    pub fn kind(self) -> LossKind {
        LossKind::namespaced("iges", self.code(), self.shared_taxonomy())
    }

    /// Build a [`LossNote`] for this code with the given per-instance message.
    ///
    /// The structured code is `iges/<local>`; the message is the per-instance
    /// text only. Severity comes from the local code and the strict floor from
    /// the shared taxonomy.
    #[must_use]
    pub fn note(self, message: impl Into<String>) -> LossNote {
        LossNote::new(self.kind(), message).with_severity(self.severity())
    }
}

#[cfg(test)]
mod tests {
    use super::IgesLossCode;
    use std::collections::BTreeSet;

    /// Value-level golden: the stable string form of every code, pinned.
    #[test]
    fn code_strings_are_pinned() {
        let codes: Vec<&str> = IgesLossCode::ALL.iter().map(|c| c.code()).collect();
        assert_eq!(
            codes,
            [
                "occurrence.expansion-output-truncated",
                "occurrence.expansion-depth-truncated",
                "occurrence.root-inference-blocked",
                "occurrence.placement-malformed",
                "entity.retained-unprojected",
                "entity.outside-envelope",
                "entity.not-projected",
                "topology.boundary-pcurve-outside-support-domain",
                "graph.pointer-unresolved",
                "parameter.boundary-ambiguous",
                "presentation.display-data-not-projected",
                "presentation.drawing-property-ambiguous",
                "presentation.line-weight-scale-unavailable",
                "geometry.ruled-developability-not-transferred",
                "geometry.spline-header-not-transferred",
                "curve.composite-carrier-degraded",
                "global.metadata-field-unusable",
                "global.semantic-context-substituted",
                "global.length-unit-unresolved",
                "global.noncanonical-framing",
                "source.dialect-unverified",
                "source.preserved-image-unavailable",
                "geometry.procedural-reduced",
                "writer.passthrough-omitted",
                "writer.minimum-resolution-adjusted",
            ]
        );
    }

    /// Codes are unique and use the stable `family.detail` kebab shape.
    #[test]
    fn codes_are_unique_and_well_formed() {
        let mut seen = BTreeSet::new();
        for code in IgesLossCode::ALL {
            let text = code.code();
            assert!(seen.insert(text), "duplicate code {text}");
            let (family, detail) = text.split_once('.').expect("family.detail shape");
            assert!(!family.is_empty() && !detail.is_empty());
            assert!(
                text.bytes()
                    .all(|b| b.is_ascii_lowercase() || b == b'.' || b == b'-'),
                "code {text} is not lowercase kebab"
            );
        }
    }

    /// The note builder fixes severity from the codec-specific code.
    #[test]
    fn note_takes_severity_from_the_code() {
        for code in IgesLossCode::ALL {
            let note = code.note("x");
            assert_eq!(note.severity, code.severity());
            assert_eq!(note.message, "x");
            assert!(note.provenance.is_none());
        }
    }
}
