// SPDX-License-Identifier: Apache-2.0
//! Stable loss vocabulary for IGES decoding and writing.
//!
//! Every fallback, approximation, and drop the codec reports carries a stable
//! machine-readable code from [`IgesLossCode`]. Codes are the gating surface:
//! harness oracles and downstream tooling key on them, never on the
//! human-readable message text, so a reworded message is not a contract change
//! and a new drop path without a code does not compile.
//!
//! [`IgesLossCode::note`] is the single construction path for a
//! [`LossNote`] in this crate: it fixes the shared loss category and the
//! severity from the code so the two cannot drift apart across sites, and it
//! leaves only the per-instance message to the caller. Local codes appear on
//! [`LossNote::code`] under the `iges` namespace.
//!
//! [`IgesLossCode::shared_taxonomy`] is an exhaustive match with no fall-through
//! arm. A default arm would silently assign a category to a code added later,
//! and the categories this codec spans (decode, entity, graph, presentation,
//! geometry, writer) have no honest common default.

use cadmpeg_ir::report::{LossKind, LossNote, LossTaxonomy, Severity};

/// A stable, machine-readable identifier for one IGES transfer loss.
///
/// Variants are grouped by the record family whose transfer degraded. The
/// string form (via [`IgesLossCode::code`]) is the stable contract.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum IgesLossCode {
    /// Product-occurrence expansion stopped at the configured output limit.
    OccurrenceExpansionOutputTruncated,
    /// Product-occurrence expansion stopped at the configured nesting-depth limit.
    OccurrenceExpansionDepthTruncated,
    /// Product-occurrence root inference was suppressed by a malformed member list.
    OccurrenceRootInferenceBlocked,
    /// Product-occurrence expansion omitted a definition or instance rejected by structure validation.
    OccurrenceInvalidStructure,
    /// An envelope-admitted entity was retained without a neutral projection.
    EntityRetainedUnprojected,
    /// An entity type/form is outside the Fixed ASCII mechanical/document envelope.
    EntityOutsideEnvelope,
    /// An entity was not projected; the instance message names the reason.
    EntityNotProjected,
    /// A Directory Entry pointer did not resolve to the expected target.
    PointerUnresolved,
    /// More than one unregistered trailing pointer-group boundary is valid.
    AmbiguousTrailingPointerGroups,
    /// Directory display, font, or color data was not projected.
    DisplayDataNotProjected,
    /// A Type 102 composite has no exact concatenated carrier.
    CompositeCarrierDegraded,
    /// Preserved source image required for a byte-exact write was unavailable.
    PreservedSourceUnavailable,
    /// Procedural definitions were reduced to writable solved carriers.
    ProceduralReduced,
    /// A native passthrough arena is not regenerated by the semantic writer.
    PassthroughRecordOmitted,
}

impl IgesLossCode {
    /// Every code, in declaration order.
    #[cfg(test)]
    pub const ALL: &'static [IgesLossCode] = &[
        Self::OccurrenceExpansionOutputTruncated,
        Self::OccurrenceExpansionDepthTruncated,
        Self::OccurrenceRootInferenceBlocked,
        Self::OccurrenceInvalidStructure,
        Self::EntityRetainedUnprojected,
        Self::EntityOutsideEnvelope,
        Self::EntityNotProjected,
        Self::PointerUnresolved,
        Self::AmbiguousTrailingPointerGroups,
        Self::DisplayDataNotProjected,
        Self::CompositeCarrierDegraded,
        Self::PreservedSourceUnavailable,
        Self::ProceduralReduced,
        Self::PassthroughRecordOmitted,
    ];

    /// The stable string identifier. This is the gating contract.
    #[must_use]
    pub const fn code(self) -> &'static str {
        match self {
            Self::OccurrenceExpansionOutputTruncated => "occurrence.expansion-output-truncated",
            Self::OccurrenceExpansionDepthTruncated => "occurrence.expansion-depth-truncated",
            Self::OccurrenceRootInferenceBlocked => "occurrence.root-inference-blocked",
            Self::OccurrenceInvalidStructure => "occurrence.invalid-structure",
            Self::EntityRetainedUnprojected => "entity.retained-unprojected",
            Self::EntityOutsideEnvelope => "entity.outside-envelope",
            Self::EntityNotProjected => "entity.not-projected",
            Self::PointerUnresolved => "graph.pointer-unresolved",
            Self::AmbiguousTrailingPointerGroups => "parameter.ambiguous-trailing-pointer-groups",
            Self::DisplayDataNotProjected => "presentation.display-data-not-projected",
            Self::CompositeCarrierDegraded => "curve.composite-carrier-degraded",
            Self::PreservedSourceUnavailable => "source.preserved-image-unavailable",
            Self::ProceduralReduced => "geometry.procedural-reduced",
            Self::PassthroughRecordOmitted => "writer.passthrough-omitted",
        }
    }

    /// The severity of this loss.
    #[must_use]
    pub const fn severity(self) -> Severity {
        match self {
            Self::PreservedSourceUnavailable => Severity::Blocking,
            Self::ProceduralReduced => Severity::Info,
            Self::OccurrenceExpansionOutputTruncated
            | Self::OccurrenceExpansionDepthTruncated
            | Self::OccurrenceRootInferenceBlocked
            | Self::OccurrenceInvalidStructure
            | Self::EntityRetainedUnprojected
            | Self::EntityOutsideEnvelope
            | Self::EntityNotProjected
            | Self::PointerUnresolved
            | Self::AmbiguousTrailingPointerGroups
            | Self::DisplayDataNotProjected
            | Self::CompositeCarrierDegraded
            | Self::PassthroughRecordOmitted => Severity::Warning,
        }
    }

    /// The shared cross-codec category this loss reports under.
    const fn shared_taxonomy(self) -> LossTaxonomy {
        match self {
            Self::OccurrenceExpansionOutputTruncated
            | Self::OccurrenceExpansionDepthTruncated
            | Self::OccurrenceRootInferenceBlocked
            | Self::OccurrenceInvalidStructure => LossTaxonomy::DecodeDiagnostic,
            Self::EntityRetainedUnprojected
            | Self::EntityOutsideEnvelope
            | Self::EntityNotProjected => LossTaxonomy::RecordNotTyped,
            Self::PointerUnresolved => LossTaxonomy::ReferenceGraphNotClosed,
            Self::AmbiguousTrailingPointerGroups => LossTaxonomy::DecodeDiagnostic,
            Self::DisplayDataNotProjected => LossTaxonomy::MaterialNotTransferred,
            Self::CompositeCarrierDegraded => LossTaxonomy::GeometryNotTransferred,
            Self::PreservedSourceUnavailable => LossTaxonomy::PreservedSourceUnavailable,
            Self::ProceduralReduced => LossTaxonomy::ProceduralReduced,
            Self::PassthroughRecordOmitted => LossTaxonomy::PassthroughRecordOmitted,
        }
    }

    /// Strict floor pinned from this local code (independent of taxonomy remap).
    ///
    /// Defaults to the taxonomy floor so a later local→taxonomy remap cannot
    /// silently change rejection; list only intentional overrides here.
    const fn strict_floor(self) -> Option<Severity> {
        self.shared_taxonomy().strict_floor()
    }

    /// Namespaced [`LossKind`] for this local code (taxonomy + pinned floor).
    #[must_use]
    pub fn kind(self) -> LossKind {
        LossKind::namespaced("iges", self.code(), self.shared_taxonomy())
            .with_strict_floor(self.strict_floor())
    }

    /// Build a [`LossNote`] for this code with the given per-instance message.
    ///
    /// The structured code is `iges/<local>`; the message is the per-instance
    /// text only. Severity and strict floor come from the local code.
    #[must_use]
    pub fn note(self, message: impl Into<String>) -> LossNote {
        LossNote::new(self.kind(), message).with_severity(self.severity())
    }
}

#[cfg(test)]
mod tests {
    use super::IgesLossCode;
    use std::collections::BTreeSet;

    /// Value-level golden: the stable string form of every code, pinned.
    #[test]
    fn code_strings_are_pinned() {
        let codes: Vec<&str> = IgesLossCode::ALL.iter().map(|c| c.code()).collect();
        assert_eq!(
            codes,
            [
                "occurrence.expansion-output-truncated",
                "occurrence.expansion-depth-truncated",
                "occurrence.root-inference-blocked",
                "occurrence.invalid-structure",
                "entity.retained-unprojected",
                "entity.outside-envelope",
                "entity.not-projected",
                "graph.pointer-unresolved",
                "parameter.ambiguous-trailing-pointer-groups",
                "presentation.display-data-not-projected",
                "curve.composite-carrier-degraded",
                "source.preserved-image-unavailable",
                "geometry.procedural-reduced",
                "writer.passthrough-omitted",
            ]
        );
    }

    /// Codes are unique and use the stable `family.detail` kebab shape.
    #[test]
    fn codes_are_unique_and_well_formed() {
        let mut seen = BTreeSet::new();
        for code in IgesLossCode::ALL {
            let text = code.code();
            assert!(seen.insert(text), "duplicate code {text}");
            let (family, detail) = text.split_once('.').expect("family.detail shape");
            assert!(!family.is_empty() && !detail.is_empty());
            assert!(
                text.bytes()
                    .all(|b| b.is_ascii_lowercase() || b == b'.' || b == b'-'),
                "code {text} is not lowercase kebab"
            );
        }
    }

    /// The note builder fixes severity from the codec-specific code.
    #[test]
    fn note_takes_severity_from_the_code() {
        for code in IgesLossCode::ALL {
            let note = code.note("x");
            assert_eq!(note.severity, code.severity());
            assert_eq!(note.message, "x");
            assert!(note.provenance.is_none());
        }
    }
}
