// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// The generated row array is checked as an artifact, not read at runtime.
#![allow(dead_code)]

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const STANDARD_NESTED_STR: &str = "catia:standard-nested";
#[rustfmt::skip]
pub(super) const STANDARD_NESTED: DialectId = DialectId::pinned(STANDARD_NESTED_STR);
#[rustfmt::skip]
pub(super) const FBB_ONLY_STR: &str = "catia:fbb-only";
#[rustfmt::skip]
pub(super) const FBB_ONLY: DialectId = DialectId::pinned(FBB_ONLY_STR);
#[rustfmt::skip]
pub(super) const E5_STREAM_STR: &str = "catia:e5-stream";
#[rustfmt::skip]
pub(super) const E5_STREAM: DialectId = DialectId::pinned(E5_STREAM_STR);
#[rustfmt::skip]
pub(super) const ZERO_ENTITY_STR: &str = "catia:zero-entity";
#[rustfmt::skip]
pub(super) const ZERO_ENTITY: DialectId = DialectId::pinned(ZERO_ENTITY_STR);
#[rustfmt::skip]
pub(super) const FLOAT_PACKED_INNER_NO_FBB_STR: &str = "catia:float-packed-inner-no-fbb";
#[rustfmt::skip]
pub(super) const FLOAT_PACKED_INNER_NO_FBB: DialectId = DialectId::pinned(FLOAT_PACKED_INNER_NO_FBB_STR);
#[rustfmt::skip]
pub(super) const INNER_NO_DIRECTORY_STR: &str = "catia:inner-no-directory";
#[rustfmt::skip]
pub(super) const INNER_NO_DIRECTORY: DialectId = DialectId::pinned(INNER_NO_DIRECTORY_STR);
#[rustfmt::skip]
pub(super) const UNKNOWN_STR: &str = "catia:unknown";
#[rustfmt::skip]
pub(super) const UNKNOWN: DialectId = DialectId::pinned(UNKNOWN_STR);

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 7] = [
    STANDARD_NESTED,
    FBB_ONLY,
    E5_STREAM,
    ZERO_ENTITY,
    FLOAT_PACKED_INNER_NO_FBB,
    INNER_NO_DIRECTORY,
    UNKNOWN,
];
