// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// Unit tests compare this registry-owned list with the codec-owned enum.

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 7] = [
    DialectId::pinned("catia:standard-nested"),
    DialectId::pinned("catia:fbb-only"),
    DialectId::pinned("catia:e5-stream"),
    DialectId::pinned("catia:zero-entity"),
    DialectId::pinned("catia:float-packed-inner-no-fbb"),
    DialectId::pinned("catia:inner-no-directory"),
    DialectId::pinned("catia:unknown"),
];
