// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/check-dialects.py from docs/dialects.toml.
// Do not edit this file directly.

/// Registry-owned format namespace.
pub(crate) const FORMAT: &str = "catia";

/// Registry-owned dialect id `catia:standard-nested`.
pub(crate) const CATIA_STANDARD_NESTED: DialectId = DialectId::pinned("catia:standard-nested");
/// Registry-owned dialect id `catia:fbb-only`.
pub(crate) const CATIA_FBB_ONLY: DialectId = DialectId::pinned("catia:fbb-only");
/// Registry-owned dialect id `catia:e5-stream`.
pub(crate) const CATIA_E5_STREAM: DialectId = DialectId::pinned("catia:e5-stream");
/// Registry-owned dialect id `catia:zero-entity`.
pub(crate) const CATIA_ZERO_ENTITY: DialectId = DialectId::pinned("catia:zero-entity");
/// Registry-owned dialect id `catia:float-packed-inner-no-fbb`.
pub(crate) const CATIA_FLOAT_PACKED_INNER_NO_FBB: DialectId = DialectId::pinned("catia:float-packed-inner-no-fbb");
/// Registry-owned dialect id `catia:inner-no-directory`.
pub(crate) const CATIA_INNER_NO_DIRECTORY: DialectId = DialectId::pinned("catia:inner-no-directory");
/// Registry-owned dialect id `catia:unknown`.
pub(crate) const CATIA_UNKNOWN: DialectId = DialectId::pinned("catia:unknown");
