// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// The generated row array is checked as an artifact, not read at runtime.
#![allow(dead_code)]

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const SW_VERSION_PRE_12000_STR: &str = "sldprt:sw-version-pre-12000";
#[rustfmt::skip]
pub(super) const SW_VERSION_PRE_12000: DialectId = DialectId::pinned(SW_VERSION_PRE_12000_STR);
#[rustfmt::skip]
pub(super) const SW_VERSION_12000_PLUS_STR: &str = "sldprt:sw-version-12000-plus";
#[rustfmt::skip]
pub(super) const SW_VERSION_12000_PLUS: DialectId = DialectId::pinned(SW_VERSION_12000_PLUS_STR);
#[rustfmt::skip]
pub(super) const UNKNOWN_STR: &str = "sldprt:unknown";
#[rustfmt::skip]
pub(super) const UNKNOWN: DialectId = DialectId::pinned(UNKNOWN_STR);

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 3] = [
    SW_VERSION_PRE_12000,
    SW_VERSION_12000_PLUS,
    UNKNOWN,
];
