// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/check-dialects.py from docs/dialects.toml.
// Do not edit this file directly.

/// Registry-owned format namespace.
pub(crate) const FORMAT: &str = "sldprt";

/// Registry-owned dialect id `sldprt:sw-version-pre-12000`.
pub(crate) const SLDPRT_SW_VERSION_PRE_12000: DialectId = DialectId::pinned("sldprt:sw-version-pre-12000");
/// Registry-owned dialect id `sldprt:sw-version-12000-plus`.
pub(crate) const SLDPRT_SW_VERSION_12000_PLUS: DialectId = DialectId::pinned("sldprt:sw-version-12000-plus");
/// Registry-owned dialect id `sldprt:unknown`.
pub(crate) const SLDPRT_UNKNOWN: DialectId = DialectId::pinned("sldprt:unknown");
