// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// The generated row array is checked as an artifact, not read at runtime.
#![allow(dead_code)]

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const AP203_E1_STR: &str = "step:ap203-e1";
#[rustfmt::skip]
pub(super) const AP203_E1: DialectId = DialectId::pinned(AP203_E1_STR);
#[rustfmt::skip]
pub(super) const AP203_E2_STR: &str = "step:ap203-e2";
#[rustfmt::skip]
pub(super) const AP203_E2: DialectId = DialectId::pinned(AP203_E2_STR);
#[rustfmt::skip]
pub(super) const AP214_STR: &str = "step:ap214";
#[rustfmt::skip]
pub(super) const AP214: DialectId = DialectId::pinned(AP214_STR);
#[rustfmt::skip]
pub(super) const AP242_STR: &str = "step:ap242";
#[rustfmt::skip]
pub(super) const AP242: DialectId = DialectId::pinned(AP242_STR);
#[rustfmt::skip]
pub(super) const AP242_E1_STR: &str = "step:ap242-e1";
#[rustfmt::skip]
pub(super) const AP242_E1: DialectId = DialectId::pinned(AP242_E1_STR);
#[rustfmt::skip]
pub(super) const AP242_E2_STR: &str = "step:ap242-e2";
#[rustfmt::skip]
pub(super) const AP242_E2: DialectId = DialectId::pinned(AP242_E2_STR);
#[rustfmt::skip]
pub(super) const AP242_E3_STR: &str = "step:ap242-e3";
#[rustfmt::skip]
pub(super) const AP242_E3: DialectId = DialectId::pinned(AP242_E3_STR);
#[rustfmt::skip]
pub(super) const PART28_XML_STR: &str = "step:part28-xml";
#[rustfmt::skip]
pub(super) const PART28_XML: DialectId = DialectId::pinned(PART28_XML_STR);
#[rustfmt::skip]
pub(super) const AP242_BO_MODEL_XML_STR: &str = "step:ap242-bo-model-xml";
#[rustfmt::skip]
pub(super) const AP242_BO_MODEL_XML: DialectId = DialectId::pinned(AP242_BO_MODEL_XML_STR);
#[rustfmt::skip]
pub(super) const PART26_HDF5_STR: &str = "step:part26-hdf5";
#[rustfmt::skip]
pub(super) const PART26_HDF5: DialectId = DialectId::pinned(PART26_HDF5_STR);
#[rustfmt::skip]
pub(super) const UNKNOWN_STR: &str = "step:unknown";
#[rustfmt::skip]
pub(super) const UNKNOWN: DialectId = DialectId::pinned(UNKNOWN_STR);

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 11] = [
    AP203_E1,
    AP203_E2,
    AP214,
    AP242,
    AP242_E1,
    AP242_E2,
    AP242_E3,
    PART28_XML,
    AP242_BO_MODEL_XML,
    PART26_HDF5,
    UNKNOWN,
];
