// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// Unit tests compare this registry-owned list with the codec-owned enum.

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 11] = [
    DialectId::pinned("step:ap203-e1"),
    DialectId::pinned("step:ap203-e2"),
    DialectId::pinned("step:ap214"),
    DialectId::pinned("step:ap242"),
    DialectId::pinned("step:ap242-e1"),
    DialectId::pinned("step:ap242-e2"),
    DialectId::pinned("step:ap242-e3"),
    DialectId::pinned("step:part28-xml"),
    DialectId::pinned("step:ap242-bo-model-xml"),
    DialectId::pinned("step:part26-hdf5"),
    DialectId::pinned("step:unknown"),
];
