// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/check-dialects.py from docs/dialects.toml.
// Do not edit this file directly.

/// Registry-owned format namespace.
pub(crate) const FORMAT: &str = "step";

/// Registry-owned dialect id `step:ap203-e1`.
pub(crate) const STEP_AP203_E1: DialectId = DialectId::pinned("step:ap203-e1");
/// Registry-owned dialect id `step:ap203-e2`.
pub(crate) const STEP_AP203_E2: DialectId = DialectId::pinned("step:ap203-e2");
/// Registry-owned dialect id `step:ap214`.
pub(crate) const STEP_AP214: DialectId = DialectId::pinned("step:ap214");
/// Registry-owned dialect id `step:ap242`.
pub(crate) const STEP_AP242: DialectId = DialectId::pinned("step:ap242");
/// Registry-owned dialect id `step:ap242-e1`.
pub(crate) const STEP_AP242_E1: DialectId = DialectId::pinned("step:ap242-e1");
/// Registry-owned dialect id `step:ap242-e2`.
pub(crate) const STEP_AP242_E2: DialectId = DialectId::pinned("step:ap242-e2");
/// Registry-owned dialect id `step:ap242-e3`.
pub(crate) const STEP_AP242_E3: DialectId = DialectId::pinned("step:ap242-e3");
/// Registry-owned dialect id `step:part28-xml`.
pub(crate) const STEP_PART28_XML: DialectId = DialectId::pinned("step:part28-xml");
/// Registry-owned dialect id `step:ap242-bo-model-xml`.
pub(crate) const STEP_AP242_BO_MODEL_XML: DialectId = DialectId::pinned("step:ap242-bo-model-xml");
/// Registry-owned dialect id `step:part26-hdf5`.
pub(crate) const STEP_PART26_HDF5: DialectId = DialectId::pinned("step:part26-hdf5");
/// Registry-owned dialect id `step:unknown`.
pub(crate) const STEP_UNKNOWN: DialectId = DialectId::pinned("step:unknown");
