#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate codec-owned dialect ID constants from docs/dialects.toml."""

from __future__ import annotations

import argparse
import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OWNERS = {
    "catia": "cadmpeg-codec-catia",
    "creo": "cadmpeg-codec-creo",
    "f3d": "cadmpeg-codec-f3d",
    "fcstd": "cadmpeg-codec-freecad",
    "iges": "cadmpeg-codec-iges",
    "inventor": "cadmpeg-codec-inventor",
    "nx": "cadmpeg-codec-nx",
    "rhino": "cadmpeg-codec-rhino",
    "sat": "cadmpeg-codec-sat",
    "sldprt": "cadmpeg-codec-sldprt",
    "step": "cadmpeg-codec-step",
}


def constant_name(dialect_id: str) -> str:
    """Return the Rust constant name for one registry ID suffix."""
    suffix = dialect_id.split(":", 1)[1]
    name = re.sub(r"[^A-Z0-9]+", "_", suffix.upper()).strip("_")
    return f"D_{name}" if name[0].isdigit() else name


def render(format_id: str, ids: list[str]) -> str:
    """Render one generated Rust module."""
    names = [constant_name(dialect_id) for dialect_id in ids]
    if len(names) != len(set(names)):
        raise ValueError(f"{format_id}: generated constant names collide")
    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// @generated by scripts/dialect_codegen.py; do not edit.",
        "// The generated row array is checked as an artifact, not read at runtime.",
        "#![allow(dead_code)]",
        "",
        "use cadmpeg_core::dialect::DialectId;",
        "",
    ]
    for name, dialect_id in zip(names, ids, strict=True):
        lines.append("#[rustfmt::skip]")
        lines.append(f'pub(super) const {name}_STR: &str = "{dialect_id}";')
        lines.append("#[rustfmt::skip]")
        lines.append(f"pub(super) const {name}: DialectId = DialectId::pinned({name}_STR);")
    lines.extend(
        [
            "",
            "#[rustfmt::skip]",
            f"pub(super) const ROWS: [DialectId; {len(names)}] = [",
            *(f"    {name}," for name in names),
            "];",
            "",
        ]
    )
    return "\n".join(lines)


def outputs(root: Path) -> dict[Path, str]:
    """Return every generated path and its expected content."""
    with (root / "docs/dialects.toml").open("rb") as handle:
        rows = tomllib.load(handle).get("dialect", [])
    by_format = {format_id: [] for format_id in OWNERS}
    for row in rows:
        if not isinstance(row, dict):
            continue
        dialect_id = row.get("id")
        if not isinstance(dialect_id, str) or ":" not in dialect_id:
            continue
        format_id = dialect_id.split(":", 1)[0]
        if format_id in by_format:
            by_format[format_id].append(dialect_id)
    return {
        root / "crates" / crate / "src/dialect/generated.rs": render(format_id, by_format[format_id])
        for format_id, crate in OWNERS.items()
        if by_format[format_id] and (root / "crates" / crate).is_dir()
    }


def check(root: Path) -> list[str]:
    """Return stale or missing generated-file failures."""
    failures = []
    for path, expected in outputs(root).items():
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            actual = None
        if actual != expected:
            failures.append(
                f"{path.relative_to(root)}: stale; run python3 scripts/dialect_codegen.py"
            )
    return failures


def write(root: Path) -> None:
    """Regenerate every codec-owned module."""
    for path, content in outputs(root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("root", nargs="?", type=Path, default=ROOT)
    args = parser.parse_args()
    root = args.root.resolve()
    if args.check:
        failures = check(root)
        for failure in failures:
            print(f"error: {failure}")
        return int(bool(failures))
    write(root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
