#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate codec-owned dialect ID constants from docs/dialects.toml."""

from __future__ import annotations

import argparse
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OWNERS = {
    "catia": "cadmpeg-codec-catia",
    "creo": "cadmpeg-codec-creo",
    "f3d": "cadmpeg-codec-f3d",
    "fcstd": "cadmpeg-codec-freecad",
    "iges": "cadmpeg-codec-iges",
    "inventor": "cadmpeg-codec-inventor",
    "nx": "cadmpeg-codec-nx",
    "rhino": "cadmpeg-codec-rhino",
    "sat": "cadmpeg-codec-sat",
    "sldprt": "cadmpeg-codec-sldprt",
    "step": "cadmpeg-codec-step",
}

# These namespaces have shared owners instead of host-codec generated modules.
# `cadmpeg-asm` closes `acis:` directly; `cadmpeg-container::parasolid` closes
# the embedded Parasolid classifier shared by NX and SLDPRT.
INTENTIONALLY_UNOWNED_FORMATS = frozenset({"acis", "parasolid"})


class CodegenError(ValueError):
    """The registry cannot be assigned completely to code-generation owners."""


def render(ids: list[str]) -> str:
    """Render the registry rows one codec enum must cover exactly."""
    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// @generated by scripts/dialect_codegen.py; do not edit.",
        "// Unit tests compare this registry-owned list with the codec-owned enum.",
        "",
        "use cadmpeg_core::dialect::DialectId;",
        "",
        "#[rustfmt::skip]",
        f"pub(super) const ROWS: [DialectId; {len(ids)}] = [",
        *(f'    DialectId::pinned("{dialect_id}"),' for dialect_id in ids),
        "];",
        "",
    ]
    return "\n".join(lines)


def outputs(root: Path) -> dict[Path, str]:
    """Return every generated path and its expected content."""
    with (root / "docs/dialects.toml").open("rb") as handle:
        rows = tomllib.load(handle).get("dialect", [])
    by_format = {format_id: [] for format_id in OWNERS}
    unmapped: set[str] = set()
    for row in rows:
        if not isinstance(row, dict):
            continue
        dialect_id = row.get("id")
        if not isinstance(dialect_id, str) or ":" not in dialect_id:
            continue
        format_id = dialect_id.split(":", 1)[0]
        if format_id in by_format:
            by_format[format_id].append(dialect_id)
        elif format_id not in INTENTIONALLY_UNOWNED_FORMATS:
            unmapped.add(format_id)
    if unmapped:
        names = ", ".join(sorted(unmapped))
        raise CodegenError(
            f"unmapped dialect format namespace(s): {names}; add an OWNERS mapping or an "
            "INTENTIONALLY_UNOWNED_FORMATS justification"
        )
    return {
        root / "crates" / crate / "src/dialect/generated.rs": render(by_format[format_id])
        for format_id, crate in OWNERS.items()
        if by_format[format_id] and (root / "crates" / crate).is_dir()
    }


def check(root: Path) -> list[str]:
    """Return stale or missing generated-file failures."""
    failures = []
    try:
        expected_outputs = outputs(root)
    except CodegenError as error:
        return [str(error)]
    for path, expected in expected_outputs.items():
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            actual = None
        if actual != expected:
            failures.append(
                f"{path.relative_to(root)}: stale; run python3 scripts/dialect_codegen.py"
            )
    return failures


def write(root: Path) -> None:
    """Regenerate every codec-owned module."""
    for path, content in outputs(root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("root", nargs="?", type=Path, default=ROOT)
    args = parser.parse_args()
    root = args.root.resolve()
    if args.check:
        failures = check(root)
        for failure in failures:
            print(f"error: {failure}")
        return int(bool(failures))
    try:
        write(root)
    except CodegenError as error:
        print(f"error: {error}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
