// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// The generated row array is checked as an artifact, not read at runtime.
#![allow(dead_code)]

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const SCHEMA_2_STR: &str = "fcstd:schema-2";
#[rustfmt::skip]
pub(super) const SCHEMA_2: DialectId = DialectId::pinned(SCHEMA_2_STR);
#[rustfmt::skip]
pub(super) const SCHEMA_3_STR: &str = "fcstd:schema-3";
#[rustfmt::skip]
pub(super) const SCHEMA_3: DialectId = DialectId::pinned(SCHEMA_3_STR);
#[rustfmt::skip]
pub(super) const SCHEMA_4_STR: &str = "fcstd:schema-4";
#[rustfmt::skip]
pub(super) const SCHEMA_4: DialectId = DialectId::pinned(SCHEMA_4_STR);
#[rustfmt::skip]
pub(super) const UNKNOWN_STR: &str = "fcstd:unknown";
#[rustfmt::skip]
pub(super) const UNKNOWN: DialectId = DialectId::pinned(UNKNOWN_STR);

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 4] = [
    SCHEMA_2,
    SCHEMA_3,
    SCHEMA_4,
    UNKNOWN,
];
