// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// The generated row array is checked as an artifact, not read at runtime.
#![allow(dead_code)]

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const D_1_0_FIXED_ASCII_STR: &str = "iges:1.0-fixed-ascii";
#[rustfmt::skip]
pub(super) const D_1_0_FIXED_ASCII: DialectId = DialectId::pinned(D_1_0_FIXED_ASCII_STR);
#[rustfmt::skip]
pub(super) const ANSI_Y14_26M_1981_FIXED_ASCII_STR: &str = "iges:ansi-y14.26m-1981-fixed-ascii";
#[rustfmt::skip]
pub(super) const ANSI_Y14_26M_1981_FIXED_ASCII: DialectId = DialectId::pinned(ANSI_Y14_26M_1981_FIXED_ASCII_STR);
#[rustfmt::skip]
pub(super) const D_2_0_FIXED_ASCII_STR: &str = "iges:2.0-fixed-ascii";
#[rustfmt::skip]
pub(super) const D_2_0_FIXED_ASCII: DialectId = DialectId::pinned(D_2_0_FIXED_ASCII_STR);
#[rustfmt::skip]
pub(super) const D_3_0_FIXED_ASCII_STR: &str = "iges:3.0-fixed-ascii";
#[rustfmt::skip]
pub(super) const D_3_0_FIXED_ASCII: DialectId = DialectId::pinned(D_3_0_FIXED_ASCII_STR);
#[rustfmt::skip]
pub(super) const ASME_ANSI_Y14_26M_1987_FIXED_ASCII_STR: &str = "iges:asme-ansi-y14.26m-1987-fixed-ascii";
#[rustfmt::skip]
pub(super) const ASME_ANSI_Y14_26M_1987_FIXED_ASCII: DialectId = DialectId::pinned(ASME_ANSI_Y14_26M_1987_FIXED_ASCII_STR);
#[rustfmt::skip]
pub(super) const D_4_0_FIXED_ASCII_STR: &str = "iges:4.0-fixed-ascii";
#[rustfmt::skip]
pub(super) const D_4_0_FIXED_ASCII: DialectId = DialectId::pinned(D_4_0_FIXED_ASCII_STR);
#[rustfmt::skip]
pub(super) const ASME_Y14_26M_1989_FIXED_ASCII_STR: &str = "iges:asme-y14.26m-1989-fixed-ascii";
#[rustfmt::skip]
pub(super) const ASME_Y14_26M_1989_FIXED_ASCII: DialectId = DialectId::pinned(ASME_Y14_26M_1989_FIXED_ASCII_STR);
#[rustfmt::skip]
pub(super) const D_5_0_FIXED_ASCII_STR: &str = "iges:5.0-fixed-ascii";
#[rustfmt::skip]
pub(super) const D_5_0_FIXED_ASCII: DialectId = DialectId::pinned(D_5_0_FIXED_ASCII_STR);
#[rustfmt::skip]
pub(super) const D_5_1_FIXED_ASCII_STR: &str = "iges:5.1-fixed-ascii";
#[rustfmt::skip]
pub(super) const D_5_1_FIXED_ASCII: DialectId = DialectId::pinned(D_5_1_FIXED_ASCII_STR);
#[rustfmt::skip]
pub(super) const D_5_2_FIXED_ASCII_STR: &str = "iges:5.2-fixed-ascii";
#[rustfmt::skip]
pub(super) const D_5_2_FIXED_ASCII: DialectId = DialectId::pinned(D_5_2_FIXED_ASCII_STR);
#[rustfmt::skip]
pub(super) const D_5_3_FIXED_ASCII_STR: &str = "iges:5.3-fixed-ascii";
#[rustfmt::skip]
pub(super) const D_5_3_FIXED_ASCII: DialectId = DialectId::pinned(D_5_3_FIXED_ASCII_STR);
#[rustfmt::skip]
pub(super) const D_4_0_COMPRESSED_ASCII_STR: &str = "iges:4.0-compressed-ascii";
#[rustfmt::skip]
pub(super) const D_4_0_COMPRESSED_ASCII: DialectId = DialectId::pinned(D_4_0_COMPRESSED_ASCII_STR);
#[rustfmt::skip]
pub(super) const D_5_0_COMPRESSED_ASCII_STR: &str = "iges:5.0-compressed-ascii";
#[rustfmt::skip]
pub(super) const D_5_0_COMPRESSED_ASCII: DialectId = DialectId::pinned(D_5_0_COMPRESSED_ASCII_STR);
#[rustfmt::skip]
pub(super) const D_5_1_COMPRESSED_ASCII_STR: &str = "iges:5.1-compressed-ascii";
#[rustfmt::skip]
pub(super) const D_5_1_COMPRESSED_ASCII: DialectId = DialectId::pinned(D_5_1_COMPRESSED_ASCII_STR);
#[rustfmt::skip]
pub(super) const D_5_2_COMPRESSED_ASCII_STR: &str = "iges:5.2-compressed-ascii";
#[rustfmt::skip]
pub(super) const D_5_2_COMPRESSED_ASCII: DialectId = DialectId::pinned(D_5_2_COMPRESSED_ASCII_STR);
#[rustfmt::skip]
pub(super) const D_5_3_COMPRESSED_ASCII_STR: &str = "iges:5.3-compressed-ascii";
#[rustfmt::skip]
pub(super) const D_5_3_COMPRESSED_ASCII: DialectId = DialectId::pinned(D_5_3_COMPRESSED_ASCII_STR);
#[rustfmt::skip]
pub(super) const D_4_0_BINARY_STR: &str = "iges:4.0-binary";
#[rustfmt::skip]
pub(super) const D_4_0_BINARY: DialectId = DialectId::pinned(D_4_0_BINARY_STR);
#[rustfmt::skip]
pub(super) const D_5_0_BINARY_STR: &str = "iges:5.0-binary";
#[rustfmt::skip]
pub(super) const D_5_0_BINARY: DialectId = DialectId::pinned(D_5_0_BINARY_STR);
#[rustfmt::skip]
pub(super) const D_5_1_BINARY_STR: &str = "iges:5.1-binary";
#[rustfmt::skip]
pub(super) const D_5_1_BINARY: DialectId = DialectId::pinned(D_5_1_BINARY_STR);
#[rustfmt::skip]
pub(super) const D_5_2_BINARY_STR: &str = "iges:5.2-binary";
#[rustfmt::skip]
pub(super) const D_5_2_BINARY: DialectId = DialectId::pinned(D_5_2_BINARY_STR);
#[rustfmt::skip]
pub(super) const D_5_3_BINARY_STR: &str = "iges:5.3-binary";
#[rustfmt::skip]
pub(super) const D_5_3_BINARY: DialectId = DialectId::pinned(D_5_3_BINARY_STR);
#[rustfmt::skip]
pub(super) const UNKNOWN_STR: &str = "iges:unknown";
#[rustfmt::skip]
pub(super) const UNKNOWN: DialectId = DialectId::pinned(UNKNOWN_STR);

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 22] = [
    D_1_0_FIXED_ASCII,
    ANSI_Y14_26M_1981_FIXED_ASCII,
    D_2_0_FIXED_ASCII,
    D_3_0_FIXED_ASCII,
    ASME_ANSI_Y14_26M_1987_FIXED_ASCII,
    D_4_0_FIXED_ASCII,
    ASME_Y14_26M_1989_FIXED_ASCII,
    D_5_0_FIXED_ASCII,
    D_5_1_FIXED_ASCII,
    D_5_2_FIXED_ASCII,
    D_5_3_FIXED_ASCII,
    D_4_0_COMPRESSED_ASCII,
    D_5_0_COMPRESSED_ASCII,
    D_5_1_COMPRESSED_ASCII,
    D_5_2_COMPRESSED_ASCII,
    D_5_3_COMPRESSED_ASCII,
    D_4_0_BINARY,
    D_5_0_BINARY,
    D_5_1_BINARY,
    D_5_2_BINARY,
    D_5_3_BINARY,
    UNKNOWN,
];
