// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// Unit tests compare this registry-owned list with the codec-owned enum.

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 22] = [
    DialectId::pinned("iges:1.0-fixed-ascii"),
    DialectId::pinned("iges:ansi-y14.26m-1981-fixed-ascii"),
    DialectId::pinned("iges:2.0-fixed-ascii"),
    DialectId::pinned("iges:3.0-fixed-ascii"),
    DialectId::pinned("iges:asme-ansi-y14.26m-1987-fixed-ascii"),
    DialectId::pinned("iges:4.0-fixed-ascii"),
    DialectId::pinned("iges:asme-y14.26m-1989-fixed-ascii"),
    DialectId::pinned("iges:5.0-fixed-ascii"),
    DialectId::pinned("iges:5.1-fixed-ascii"),
    DialectId::pinned("iges:5.2-fixed-ascii"),
    DialectId::pinned("iges:5.3-fixed-ascii"),
    DialectId::pinned("iges:4.0-compressed-ascii"),
    DialectId::pinned("iges:5.0-compressed-ascii"),
    DialectId::pinned("iges:5.1-compressed-ascii"),
    DialectId::pinned("iges:5.2-compressed-ascii"),
    DialectId::pinned("iges:5.3-compressed-ascii"),
    DialectId::pinned("iges:4.0-binary"),
    DialectId::pinned("iges:5.0-binary"),
    DialectId::pinned("iges:5.1-binary"),
    DialectId::pinned("iges:5.2-binary"),
    DialectId::pinned("iges:5.3-binary"),
    DialectId::pinned("iges:unknown"),
];
