// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/check-dialects.py from docs/dialects.toml.
// Do not edit this file directly.

/// Registry-owned format namespace.
pub(crate) const FORMAT: &str = "iges";

/// Registry-owned dialect id `iges:1.0-fixed-ascii`.
pub(crate) const IGES_1_0_FIXED_ASCII: DialectId = DialectId::pinned("iges:1.0-fixed-ascii");
/// Registry-owned dialect id `iges:ansi-y14.26m-1981-fixed-ascii`.
pub(crate) const IGES_ANSI_Y14_26M_1981_FIXED_ASCII: DialectId = DialectId::pinned("iges:ansi-y14.26m-1981-fixed-ascii");
/// Registry-owned dialect id `iges:2.0-fixed-ascii`.
pub(crate) const IGES_2_0_FIXED_ASCII: DialectId = DialectId::pinned("iges:2.0-fixed-ascii");
/// Registry-owned dialect id `iges:3.0-fixed-ascii`.
pub(crate) const IGES_3_0_FIXED_ASCII: DialectId = DialectId::pinned("iges:3.0-fixed-ascii");
/// Registry-owned dialect id `iges:asme-ansi-y14.26m-1987-fixed-ascii`.
pub(crate) const IGES_ASME_ANSI_Y14_26M_1987_FIXED_ASCII: DialectId = DialectId::pinned("iges:asme-ansi-y14.26m-1987-fixed-ascii");
/// Registry-owned dialect id `iges:4.0-fixed-ascii`.
pub(crate) const IGES_4_0_FIXED_ASCII: DialectId = DialectId::pinned("iges:4.0-fixed-ascii");
/// Registry-owned dialect id `iges:asme-y14.26m-1989-fixed-ascii`.
pub(crate) const IGES_ASME_Y14_26M_1989_FIXED_ASCII: DialectId = DialectId::pinned("iges:asme-y14.26m-1989-fixed-ascii");
/// Registry-owned dialect id `iges:5.0-fixed-ascii`.
pub(crate) const IGES_5_0_FIXED_ASCII: DialectId = DialectId::pinned("iges:5.0-fixed-ascii");
/// Registry-owned dialect id `iges:5.1-fixed-ascii`.
pub(crate) const IGES_5_1_FIXED_ASCII: DialectId = DialectId::pinned("iges:5.1-fixed-ascii");
/// Registry-owned dialect id `iges:5.2-fixed-ascii`.
pub(crate) const IGES_5_2_FIXED_ASCII: DialectId = DialectId::pinned("iges:5.2-fixed-ascii");
/// Registry-owned dialect id `iges:5.3-fixed-ascii`.
pub(crate) const IGES_5_3_FIXED_ASCII: DialectId = DialectId::pinned("iges:5.3-fixed-ascii");
/// Registry-owned dialect id `iges:4.0-compressed-ascii`.
pub(crate) const IGES_4_0_COMPRESSED_ASCII: DialectId = DialectId::pinned("iges:4.0-compressed-ascii");
/// Registry-owned dialect id `iges:5.0-compressed-ascii`.
pub(crate) const IGES_5_0_COMPRESSED_ASCII: DialectId = DialectId::pinned("iges:5.0-compressed-ascii");
/// Registry-owned dialect id `iges:5.1-compressed-ascii`.
pub(crate) const IGES_5_1_COMPRESSED_ASCII: DialectId = DialectId::pinned("iges:5.1-compressed-ascii");
/// Registry-owned dialect id `iges:5.2-compressed-ascii`.
pub(crate) const IGES_5_2_COMPRESSED_ASCII: DialectId = DialectId::pinned("iges:5.2-compressed-ascii");
/// Registry-owned dialect id `iges:5.3-compressed-ascii`.
pub(crate) const IGES_5_3_COMPRESSED_ASCII: DialectId = DialectId::pinned("iges:5.3-compressed-ascii");
/// Registry-owned dialect id `iges:4.0-binary`.
pub(crate) const IGES_4_0_BINARY: DialectId = DialectId::pinned("iges:4.0-binary");
/// Registry-owned dialect id `iges:5.0-binary`.
pub(crate) const IGES_5_0_BINARY: DialectId = DialectId::pinned("iges:5.0-binary");
/// Registry-owned dialect id `iges:5.1-binary`.
pub(crate) const IGES_5_1_BINARY: DialectId = DialectId::pinned("iges:5.1-binary");
/// Registry-owned dialect id `iges:5.2-binary`.
pub(crate) const IGES_5_2_BINARY: DialectId = DialectId::pinned("iges:5.2-binary");
/// Registry-owned dialect id `iges:5.3-binary`.
pub(crate) const IGES_5_3_BINARY: DialectId = DialectId::pinned("iges:5.3-binary");
/// Registry-owned dialect id `iges:unknown`.
pub(crate) const IGES_UNKNOWN: DialectId = DialectId::pinned("iges:unknown");
