// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// Unit tests compare this registry-owned list with the codec-owned enum.

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 3] = [
    DialectId::pinned("sat:asm-binary"),
    DialectId::pinned("sat:acis-binary"),
    DialectId::pinned("sat:text"),
];
