// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/dialect_codegen.py; do not edit.
// The generated row array is checked as an artifact, not read at runtime.
#![allow(dead_code)]

use cadmpeg_core::dialect::DialectId;

#[rustfmt::skip]
pub(super) const ASM_BINARY_STR: &str = "sat:asm-binary";
#[rustfmt::skip]
pub(super) const ASM_BINARY: DialectId = DialectId::pinned(ASM_BINARY_STR);
#[rustfmt::skip]
pub(super) const ACIS_BINARY_STR: &str = "sat:acis-binary";
#[rustfmt::skip]
pub(super) const ACIS_BINARY: DialectId = DialectId::pinned(ACIS_BINARY_STR);
#[rustfmt::skip]
pub(super) const TEXT_STR: &str = "sat:text";
#[rustfmt::skip]
pub(super) const TEXT: DialectId = DialectId::pinned(TEXT_STR);
#[rustfmt::skip]
pub(super) const UNKNOWN_STR: &str = "sat:unknown";
#[rustfmt::skip]
pub(super) const UNKNOWN: DialectId = DialectId::pinned(UNKNOWN_STR);

#[rustfmt::skip]
pub(super) const ROWS: [DialectId; 4] = [
    ASM_BINARY,
    ACIS_BINARY,
    TEXT,
    UNKNOWN,
];
