// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/check-dialects.py from docs/dialects.toml.
// Do not edit this file directly.

/// Registry-owned format namespace.
pub(crate) const FORMAT: &str = "sat";

/// Registry-owned dialect id `sat:asm-binary`.
pub(crate) const SAT_ASM_BINARY: DialectId = cadmpeg_core::dialect_id!("sat:asm-binary");
/// Registry-owned dialect id `sat:acis-binary`.
pub(crate) const SAT_ACIS_BINARY: DialectId = cadmpeg_core::dialect_id!("sat:acis-binary");
/// Registry-owned dialect id `sat:text`.
pub(crate) const SAT_TEXT: DialectId = cadmpeg_core::dialect_id!("sat:text");
/// Registry-owned dialect id `sat:unknown`.
// Container detection cannot produce this registry row.
#[allow(dead_code)]
pub(crate) const SAT_UNKNOWN: DialectId = cadmpeg_core::dialect_id!("sat:unknown");
